/**
 * <copyright>
 * </copyright>
 *
 * 
 */
package hydraconstraints.resource.hydraConst.grammar;

/**
 * This class provides the follow sets for all terminals of the grammar. These
 * sets are used during code completion.
 */
public class HydraConstFollowSetProvider {
	
	public final static hydraconstraints.resource.hydraConst.IHydraConstExpectedElement TERMINAL_0 = new hydraconstraints.resource.hydraConst.mopp.HydraConstExpectedCsString(hydraconstraints.resource.hydraConst.grammar.HydraConstGrammarInformationProvider.HYDRACONST_0_0_0_0);
	public final static hydraconstraints.resource.hydraConst.IHydraConstExpectedElement TERMINAL_1 = new hydraconstraints.resource.hydraConst.mopp.HydraConstExpectedStructuralFeature(hydraconstraints.resource.hydraConst.grammar.HydraConstGrammarInformationProvider.HYDRACONST_0_0_0_1);
	public final static hydraconstraints.resource.hydraConst.IHydraConstExpectedElement TERMINAL_2 = new hydraconstraints.resource.hydraConst.mopp.HydraConstExpectedCsString(hydraconstraints.resource.hydraConst.grammar.HydraConstGrammarInformationProvider.HYDRACONST_0_0_0_2);
	public final static hydraconstraints.resource.hydraConst.IHydraConstExpectedElement TERMINAL_3 = new hydraconstraints.resource.hydraConst.mopp.HydraConstExpectedCsString(hydraconstraints.resource.hydraConst.grammar.HydraConstGrammarInformationProvider.HYDRACONST_2_0_0_0);
	public final static hydraconstraints.resource.hydraConst.IHydraConstExpectedElement TERMINAL_4 = new hydraconstraints.resource.hydraConst.mopp.HydraConstExpectedStructuralFeature(hydraconstraints.resource.hydraConst.grammar.HydraConstGrammarInformationProvider.HYDRACONST_25_0_0_0);
	public final static hydraconstraints.resource.hydraConst.IHydraConstExpectedElement TERMINAL_5 = new hydraconstraints.resource.hydraConst.mopp.HydraConstExpectedCsString(hydraconstraints.resource.hydraConst.grammar.HydraConstGrammarInformationProvider.HYDRACONST_16_0_0_0);
	public final static hydraconstraints.resource.hydraConst.IHydraConstExpectedElement TERMINAL_6 = new hydraconstraints.resource.hydraConst.mopp.HydraConstExpectedCsString(hydraconstraints.resource.hydraConst.grammar.HydraConstGrammarInformationProvider.HYDRACONST_17_0_0_0);
	public final static hydraconstraints.resource.hydraConst.IHydraConstExpectedElement TERMINAL_7 = new hydraconstraints.resource.hydraConst.mopp.HydraConstExpectedStructuralFeature(hydraconstraints.resource.hydraConst.grammar.HydraConstGrammarInformationProvider.HYDRACONST_24_0_0_0);
	public final static hydraconstraints.resource.hydraConst.IHydraConstExpectedElement TERMINAL_8 = new hydraconstraints.resource.hydraConst.mopp.HydraConstExpectedCsString(hydraconstraints.resource.hydraConst.grammar.HydraConstGrammarInformationProvider.HYDRACONST_10_0_0_0);
	public final static hydraconstraints.resource.hydraConst.IHydraConstExpectedElement TERMINAL_9 = new hydraconstraints.resource.hydraConst.mopp.HydraConstExpectedStructuralFeature(hydraconstraints.resource.hydraConst.grammar.HydraConstGrammarInformationProvider.HYDRACONST_26_0_0_0);
	public final static hydraconstraints.resource.hydraConst.IHydraConstExpectedElement TERMINAL_10 = new hydraconstraints.resource.hydraConst.mopp.HydraConstExpectedCsString(hydraconstraints.resource.hydraConst.grammar.HydraConstGrammarInformationProvider.HYDRACONST_4_0_1_0);
	public final static hydraconstraints.resource.hydraConst.IHydraConstExpectedElement TERMINAL_11 = new hydraconstraints.resource.hydraConst.mopp.HydraConstExpectedCsString(hydraconstraints.resource.hydraConst.grammar.HydraConstGrammarInformationProvider.HYDRACONST_5_0_1_0);
	public final static hydraconstraints.resource.hydraConst.IHydraConstExpectedElement TERMINAL_12 = new hydraconstraints.resource.hydraConst.mopp.HydraConstExpectedCsString(hydraconstraints.resource.hydraConst.grammar.HydraConstGrammarInformationProvider.HYDRACONST_1_0_1_0);
	public final static hydraconstraints.resource.hydraConst.IHydraConstExpectedElement TERMINAL_13 = new hydraconstraints.resource.hydraConst.mopp.HydraConstExpectedCsString(hydraconstraints.resource.hydraConst.grammar.HydraConstGrammarInformationProvider.HYDRACONST_0_0_0_3_0_0_1);
	public final static hydraconstraints.resource.hydraConst.IHydraConstExpectedElement TERMINAL_14 = new hydraconstraints.resource.hydraConst.mopp.HydraConstExpectedCsString(hydraconstraints.resource.hydraConst.grammar.HydraConstGrammarInformationProvider.HYDRACONST_15_0_0_3);
	public final static hydraconstraints.resource.hydraConst.IHydraConstExpectedElement TERMINAL_15 = new hydraconstraints.resource.hydraConst.mopp.HydraConstExpectedCsString(hydraconstraints.resource.hydraConst.grammar.HydraConstGrammarInformationProvider.HYDRACONST_1_0_1_2);
	public final static hydraconstraints.resource.hydraConst.IHydraConstExpectedElement TERMINAL_16 = new hydraconstraints.resource.hydraConst.mopp.HydraConstExpectedCsString(hydraconstraints.resource.hydraConst.grammar.HydraConstGrammarInformationProvider.HYDRACONST_2_0_0_2);
	public final static hydraconstraints.resource.hydraConst.IHydraConstExpectedElement TERMINAL_17 = new hydraconstraints.resource.hydraConst.mopp.HydraConstExpectedCsString(hydraconstraints.resource.hydraConst.grammar.HydraConstGrammarInformationProvider.HYDRACONST_6_0_0_1);
	public final static hydraconstraints.resource.hydraConst.IHydraConstExpectedElement TERMINAL_18 = new hydraconstraints.resource.hydraConst.mopp.HydraConstExpectedCsString(hydraconstraints.resource.hydraConst.grammar.HydraConstGrammarInformationProvider.HYDRACONST_7_0_0_1);
	public final static hydraconstraints.resource.hydraConst.IHydraConstExpectedElement TERMINAL_19 = new hydraconstraints.resource.hydraConst.mopp.HydraConstExpectedCsString(hydraconstraints.resource.hydraConst.grammar.HydraConstGrammarInformationProvider.HYDRACONST_8_0_0_1);
	public final static hydraconstraints.resource.hydraConst.IHydraConstExpectedElement TERMINAL_20 = new hydraconstraints.resource.hydraConst.mopp.HydraConstExpectedCsString(hydraconstraints.resource.hydraConst.grammar.HydraConstGrammarInformationProvider.HYDRACONST_9_0_0_1);
	public final static hydraconstraints.resource.hydraConst.IHydraConstExpectedElement TERMINAL_21 = new hydraconstraints.resource.hydraConst.mopp.HydraConstExpectedCsString(hydraconstraints.resource.hydraConst.grammar.HydraConstGrammarInformationProvider.HYDRACONST_3_0_0_0);
	public final static hydraconstraints.resource.hydraConst.IHydraConstExpectedElement TERMINAL_22 = new hydraconstraints.resource.hydraConst.mopp.HydraConstExpectedCsString(hydraconstraints.resource.hydraConst.grammar.HydraConstGrammarInformationProvider.HYDRACONST_3_0_0_2);
	public final static hydraconstraints.resource.hydraConst.IHydraConstExpectedElement TERMINAL_23 = new hydraconstraints.resource.hydraConst.mopp.HydraConstExpectedCsString(hydraconstraints.resource.hydraConst.grammar.HydraConstGrammarInformationProvider.HYDRACONST_11_0_0_1);
	public final static hydraconstraints.resource.hydraConst.IHydraConstExpectedElement TERMINAL_24 = new hydraconstraints.resource.hydraConst.mopp.HydraConstExpectedCsString(hydraconstraints.resource.hydraConst.grammar.HydraConstGrammarInformationProvider.HYDRACONST_12_0_0_1);
	public final static hydraconstraints.resource.hydraConst.IHydraConstExpectedElement TERMINAL_25 = new hydraconstraints.resource.hydraConst.mopp.HydraConstExpectedCsString(hydraconstraints.resource.hydraConst.grammar.HydraConstGrammarInformationProvider.HYDRACONST_13_0_0_1);
	public final static hydraconstraints.resource.hydraConst.IHydraConstExpectedElement TERMINAL_26 = new hydraconstraints.resource.hydraConst.mopp.HydraConstExpectedCsString(hydraconstraints.resource.hydraConst.grammar.HydraConstGrammarInformationProvider.HYDRACONST_14_0_0_1);
	public final static hydraconstraints.resource.hydraConst.IHydraConstExpectedElement TERMINAL_27 = new hydraconstraints.resource.hydraConst.mopp.HydraConstExpectedCsString(hydraconstraints.resource.hydraConst.grammar.HydraConstGrammarInformationProvider.HYDRACONST_4_0_1_2);
	public final static hydraconstraints.resource.hydraConst.IHydraConstExpectedElement TERMINAL_28 = new hydraconstraints.resource.hydraConst.mopp.HydraConstExpectedCsString(hydraconstraints.resource.hydraConst.grammar.HydraConstGrammarInformationProvider.HYDRACONST_18_0_0_1);
	public final static hydraconstraints.resource.hydraConst.IHydraConstExpectedElement TERMINAL_29 = new hydraconstraints.resource.hydraConst.mopp.HydraConstExpectedCsString(hydraconstraints.resource.hydraConst.grammar.HydraConstGrammarInformationProvider.HYDRACONST_19_0_0_1);
	public final static hydraconstraints.resource.hydraConst.IHydraConstExpectedElement TERMINAL_30 = new hydraconstraints.resource.hydraConst.mopp.HydraConstExpectedCsString(hydraconstraints.resource.hydraConst.grammar.HydraConstGrammarInformationProvider.HYDRACONST_20_0_0_1);
	public final static hydraconstraints.resource.hydraConst.IHydraConstExpectedElement TERMINAL_31 = new hydraconstraints.resource.hydraConst.mopp.HydraConstExpectedCsString(hydraconstraints.resource.hydraConst.grammar.HydraConstGrammarInformationProvider.HYDRACONST_21_0_0_1);
	public final static hydraconstraints.resource.hydraConst.IHydraConstExpectedElement TERMINAL_32 = new hydraconstraints.resource.hydraConst.mopp.HydraConstExpectedCsString(hydraconstraints.resource.hydraConst.grammar.HydraConstGrammarInformationProvider.HYDRACONST_22_0_0_1);
	public final static hydraconstraints.resource.hydraConst.IHydraConstExpectedElement TERMINAL_33 = new hydraconstraints.resource.hydraConst.mopp.HydraConstExpectedCsString(hydraconstraints.resource.hydraConst.grammar.HydraConstGrammarInformationProvider.HYDRACONST_23_0_0_1);
	public final static hydraconstraints.resource.hydraConst.IHydraConstExpectedElement TERMINAL_34 = new hydraconstraints.resource.hydraConst.mopp.HydraConstExpectedCsString(hydraconstraints.resource.hydraConst.grammar.HydraConstGrammarInformationProvider.HYDRACONST_5_0_1_2);
	public final static hydraconstraints.resource.hydraConst.IHydraConstExpectedElement TERMINAL_35 = new hydraconstraints.resource.hydraConst.mopp.HydraConstExpectedCsString(hydraconstraints.resource.hydraConst.grammar.HydraConstGrammarInformationProvider.HYDRACONST_15_0_0_1);
	
	public final static org.eclipse.emf.ecore.EStructuralFeature FEATURE_0 = hydraconstraints.HydraconstraintsPackage.eINSTANCE.getBinaryOp().getEStructuralFeature(hydraconstraints.HydraconstraintsPackage.BINARY_OP__BINARY_OP1);
	public final static org.eclipse.emf.ecore.EStructuralFeature FEATURE_1 = hydraconstraints.HydraconstraintsPackage.eINSTANCE.getConstraint().getEStructuralFeature(hydraconstraints.HydraconstraintsPackage.CONSTRAINT__OPERATORS);
	public final static org.eclipse.emf.ecore.EStructuralFeature FEATURE_2 = hydraconstraints.HydraconstraintsPackage.eINSTANCE.getModel().getEStructuralFeature(hydraconstraints.HydraconstraintsPackage.MODEL__CONSTRAINTS);
	public final static org.eclipse.emf.ecore.EStructuralFeature FEATURE_3 = hydraconstraints.HydraconstraintsPackage.eINSTANCE.getContext().getEStructuralFeature(hydraconstraints.HydraconstraintsPackage.CONTEXT__CONTEXT_OP1);
	public final static org.eclipse.emf.ecore.EStructuralFeature FEATURE_4 = hydraconstraints.HydraconstraintsPackage.eINSTANCE.getBoolPriorityOperand1().getEStructuralFeature(hydraconstraints.HydraconstraintsPackage.BOOL_PRIORITY_OPERAND1__BOOL_PRIORITY_OP1);
	public final static org.eclipse.emf.ecore.EStructuralFeature FEATURE_5 = hydraconstraints.HydraconstraintsPackage.eINSTANCE.getNumPriorityOperand1().getEStructuralFeature(hydraconstraints.HydraconstraintsPackage.NUM_PRIORITY_OPERAND1__NUM_PRIORITY_OP1);
	public final static org.eclipse.emf.ecore.EStructuralFeature FEATURE_6 = hydraconstraints.HydraconstraintsPackage.eINSTANCE.getNumOperator().getEStructuralFeature(hydraconstraints.HydraconstraintsPackage.NUM_OPERATOR__NUM_OP1);
	public final static org.eclipse.emf.ecore.EStructuralFeature FEATURE_7 = hydraconstraints.HydraconstraintsPackage.eINSTANCE.getNumPriorityOperand2().getEStructuralFeature(hydraconstraints.HydraconstraintsPackage.NUM_PRIORITY_OPERAND2__NUM_PRIORITY_OP2);
	public final static org.eclipse.emf.ecore.EStructuralFeature FEATURE_8 = hydraconstraints.HydraconstraintsPackage.eINSTANCE.getComparison().getEStructuralFeature(hydraconstraints.HydraconstraintsPackage.COMPARISON__COMP_OP1);
	public final static org.eclipse.emf.ecore.EStructuralFeature FEATURE_9 = hydraconstraints.HydraconstraintsPackage.eINSTANCE.getBoolPriorityOperand2().getEStructuralFeature(hydraconstraints.HydraconstraintsPackage.BOOL_PRIORITY_OPERAND2__BOOL_PRIORITY_OP2);
	public final static org.eclipse.emf.ecore.EStructuralFeature FEATURE_10 = hydraconstraints.HydraconstraintsPackage.eINSTANCE.getBinaryOp().getEStructuralFeature(hydraconstraints.HydraconstraintsPackage.BINARY_OP__BINARY_OP2);
	public final static org.eclipse.emf.ecore.EStructuralFeature FEATURE_11 = hydraconstraints.HydraconstraintsPackage.eINSTANCE.getUnaryOp().getEStructuralFeature(hydraconstraints.HydraconstraintsPackage.UNARY_OP__UNARY_OP);
	public final static org.eclipse.emf.ecore.EStructuralFeature FEATURE_12 = hydraconstraints.HydraconstraintsPackage.eINSTANCE.getNumOperator().getEStructuralFeature(hydraconstraints.HydraconstraintsPackage.NUM_OPERATOR__NUM_OP2);
	public final static org.eclipse.emf.ecore.EStructuralFeature FEATURE_13 = hydraconstraints.HydraconstraintsPackage.eINSTANCE.getContext().getEStructuralFeature(hydraconstraints.HydraconstraintsPackage.CONTEXT__CONTEXT_OP2);
	public final static org.eclipse.emf.ecore.EStructuralFeature FEATURE_14 = hydraconstraints.HydraconstraintsPackage.eINSTANCE.getSelection().getEStructuralFeature(hydraconstraints.HydraconstraintsPackage.SELECTION__SELECTION_OP);
	public final static org.eclipse.emf.ecore.EStructuralFeature FEATURE_15 = hydraconstraints.HydraconstraintsPackage.eINSTANCE.getComparison().getEStructuralFeature(hydraconstraints.HydraconstraintsPackage.COMPARISON__COMP_OP2);
	
	public final static org.eclipse.emf.ecore.EStructuralFeature[] EMPTY_FEATURE_ARRAY = new org.eclipse.emf.ecore.EStructuralFeature[0];
	
	public static void wire0() {
		TERMINAL_0.addFollower(TERMINAL_1, EMPTY_FEATURE_ARRAY);
		TERMINAL_1.addFollower(TERMINAL_2, EMPTY_FEATURE_ARRAY);
		TERMINAL_2.addFollower(TERMINAL_3, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, FEATURE_1, FEATURE_2, });
		TERMINAL_2.addFollower(TERMINAL_4, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_3, FEATURE_4, FEATURE_0, FEATURE_1, FEATURE_2, });
		TERMINAL_2.addFollower(TERMINAL_5, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_4, FEATURE_0, FEATURE_1, FEATURE_2, });
		TERMINAL_2.addFollower(TERMINAL_6, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_4, FEATURE_0, FEATURE_1, FEATURE_2, });
		TERMINAL_2.addFollower(TERMINAL_7, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_4, FEATURE_0, FEATURE_1, FEATURE_2, });
		TERMINAL_2.addFollower(TERMINAL_8, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_1, FEATURE_2, });
		TERMINAL_2.addFollower(TERMINAL_9, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_5, FEATURE_6, FEATURE_7, FEATURE_8, FEATURE_1, FEATURE_2, });
		TERMINAL_2.addFollower(TERMINAL_10, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, FEATURE_7, FEATURE_8, FEATURE_1, FEATURE_2, });
		TERMINAL_2.addFollower(TERMINAL_11, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_8, FEATURE_1, FEATURE_2, });
		TERMINAL_2.addFollower(TERMINAL_12, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_2, });
		TERMINAL_13.addFollower(TERMINAL_3, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, FEATURE_1, FEATURE_2, });
		TERMINAL_13.addFollower(TERMINAL_4, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_3, FEATURE_4, FEATURE_0, FEATURE_1, FEATURE_2, });
		TERMINAL_13.addFollower(TERMINAL_5, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_4, FEATURE_0, FEATURE_1, FEATURE_2, });
		TERMINAL_13.addFollower(TERMINAL_6, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_4, FEATURE_0, FEATURE_1, FEATURE_2, });
		TERMINAL_13.addFollower(TERMINAL_7, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_4, FEATURE_0, FEATURE_1, FEATURE_2, });
		TERMINAL_13.addFollower(TERMINAL_8, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_1, FEATURE_2, });
		TERMINAL_13.addFollower(TERMINAL_9, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_5, FEATURE_6, FEATURE_7, FEATURE_8, FEATURE_1, FEATURE_2, });
		TERMINAL_13.addFollower(TERMINAL_10, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, FEATURE_7, FEATURE_8, FEATURE_1, FEATURE_2, });
		TERMINAL_13.addFollower(TERMINAL_11, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_8, FEATURE_1, FEATURE_2, });
		TERMINAL_13.addFollower(TERMINAL_12, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_2, });
		TERMINAL_12.addFollower(TERMINAL_3, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, FEATURE_1, });
		TERMINAL_12.addFollower(TERMINAL_4, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_3, FEATURE_4, FEATURE_0, FEATURE_1, });
		TERMINAL_12.addFollower(TERMINAL_5, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_4, FEATURE_0, FEATURE_1, });
		TERMINAL_12.addFollower(TERMINAL_6, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_4, FEATURE_0, FEATURE_1, });
		TERMINAL_12.addFollower(TERMINAL_7, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_4, FEATURE_0, FEATURE_1, });
		TERMINAL_12.addFollower(TERMINAL_8, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_1, });
		TERMINAL_12.addFollower(TERMINAL_9, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_5, FEATURE_6, FEATURE_7, FEATURE_8, FEATURE_1, });
		TERMINAL_12.addFollower(TERMINAL_10, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, FEATURE_7, FEATURE_8, FEATURE_1, });
		TERMINAL_12.addFollower(TERMINAL_11, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_8, FEATURE_1, });
		TERMINAL_15.addFollower(TERMINAL_13, EMPTY_FEATURE_ARRAY);
		TERMINAL_15.addFollower(TERMINAL_14, EMPTY_FEATURE_ARRAY);
		TERMINAL_3.addFollower(TERMINAL_3, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, FEATURE_4, });
		TERMINAL_3.addFollower(TERMINAL_4, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_3, FEATURE_4, FEATURE_0, FEATURE_4, });
		TERMINAL_3.addFollower(TERMINAL_5, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_4, FEATURE_0, FEATURE_4, });
		TERMINAL_3.addFollower(TERMINAL_6, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_4, FEATURE_0, FEATURE_4, });
		TERMINAL_3.addFollower(TERMINAL_7, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_4, FEATURE_0, FEATURE_4, });
		TERMINAL_3.addFollower(TERMINAL_8, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_4, });
		TERMINAL_3.addFollower(TERMINAL_9, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_5, FEATURE_6, FEATURE_7, FEATURE_8, FEATURE_4, });
		TERMINAL_3.addFollower(TERMINAL_10, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, FEATURE_7, FEATURE_8, FEATURE_4, });
		TERMINAL_3.addFollower(TERMINAL_11, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_8, FEATURE_4, });
		TERMINAL_16.addFollower(TERMINAL_17, EMPTY_FEATURE_ARRAY);
		TERMINAL_16.addFollower(TERMINAL_18, EMPTY_FEATURE_ARRAY);
		TERMINAL_16.addFollower(TERMINAL_19, EMPTY_FEATURE_ARRAY);
		TERMINAL_16.addFollower(TERMINAL_20, EMPTY_FEATURE_ARRAY);
		TERMINAL_21.addFollower(TERMINAL_3, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, FEATURE_9, });
		TERMINAL_21.addFollower(TERMINAL_4, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_3, FEATURE_4, FEATURE_0, FEATURE_9, });
		TERMINAL_21.addFollower(TERMINAL_5, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_4, FEATURE_0, FEATURE_9, });
		TERMINAL_21.addFollower(TERMINAL_6, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_4, FEATURE_0, FEATURE_9, });
		TERMINAL_21.addFollower(TERMINAL_7, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_4, FEATURE_0, FEATURE_9, });
		TERMINAL_21.addFollower(TERMINAL_8, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_9, });
		TERMINAL_21.addFollower(TERMINAL_9, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_5, FEATURE_6, FEATURE_7, FEATURE_8, FEATURE_9, });
		TERMINAL_21.addFollower(TERMINAL_10, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, FEATURE_7, FEATURE_8, FEATURE_9, });
		TERMINAL_21.addFollower(TERMINAL_11, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_8, FEATURE_9, });
		TERMINAL_22.addFollower(TERMINAL_13, EMPTY_FEATURE_ARRAY);
		TERMINAL_22.addFollower(TERMINAL_14, EMPTY_FEATURE_ARRAY);
		TERMINAL_22.addFollower(TERMINAL_16, EMPTY_FEATURE_ARRAY);
		TERMINAL_22.addFollower(TERMINAL_22, EMPTY_FEATURE_ARRAY);
		TERMINAL_10.addFollower(TERMINAL_4, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_3, FEATURE_5, FEATURE_6, FEATURE_5, });
		TERMINAL_10.addFollower(TERMINAL_9, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_5, FEATURE_6, FEATURE_5, });
		TERMINAL_10.addFollower(TERMINAL_10, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, FEATURE_5, });
		TERMINAL_27.addFollower(TERMINAL_23, EMPTY_FEATURE_ARRAY);
		TERMINAL_27.addFollower(TERMINAL_24, EMPTY_FEATURE_ARRAY);
		TERMINAL_27.addFollower(TERMINAL_25, EMPTY_FEATURE_ARRAY);
		TERMINAL_27.addFollower(TERMINAL_26, EMPTY_FEATURE_ARRAY);
		TERMINAL_11.addFollower(TERMINAL_4, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_3, FEATURE_5, FEATURE_6, FEATURE_7, });
		TERMINAL_11.addFollower(TERMINAL_9, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_5, FEATURE_6, FEATURE_7, });
		TERMINAL_11.addFollower(TERMINAL_10, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, FEATURE_7, });
		TERMINAL_34.addFollower(TERMINAL_27, EMPTY_FEATURE_ARRAY);
		TERMINAL_34.addFollower(TERMINAL_28, EMPTY_FEATURE_ARRAY);
		TERMINAL_34.addFollower(TERMINAL_29, EMPTY_FEATURE_ARRAY);
		TERMINAL_34.addFollower(TERMINAL_30, EMPTY_FEATURE_ARRAY);
		TERMINAL_34.addFollower(TERMINAL_31, EMPTY_FEATURE_ARRAY);
		TERMINAL_34.addFollower(TERMINAL_32, EMPTY_FEATURE_ARRAY);
		TERMINAL_34.addFollower(TERMINAL_33, EMPTY_FEATURE_ARRAY);
		TERMINAL_17.addFollower(TERMINAL_21, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_10, });
		TERMINAL_17.addFollower(TERMINAL_3, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, FEATURE_9, FEATURE_10, });
		TERMINAL_17.addFollower(TERMINAL_4, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_3, FEATURE_4, FEATURE_0, FEATURE_9, FEATURE_10, });
		TERMINAL_17.addFollower(TERMINAL_5, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_4, FEATURE_0, FEATURE_9, FEATURE_10, });
		TERMINAL_17.addFollower(TERMINAL_6, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_4, FEATURE_0, FEATURE_9, FEATURE_10, });
		TERMINAL_17.addFollower(TERMINAL_7, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_4, FEATURE_0, FEATURE_9, FEATURE_10, });
		TERMINAL_17.addFollower(TERMINAL_8, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_9, FEATURE_10, });
		TERMINAL_17.addFollower(TERMINAL_9, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_5, FEATURE_6, FEATURE_7, FEATURE_8, FEATURE_9, FEATURE_10, });
		TERMINAL_17.addFollower(TERMINAL_10, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, FEATURE_7, FEATURE_8, FEATURE_9, FEATURE_10, });
		TERMINAL_17.addFollower(TERMINAL_11, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_8, FEATURE_9, FEATURE_10, });
		TERMINAL_18.addFollower(TERMINAL_21, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_10, });
		TERMINAL_18.addFollower(TERMINAL_3, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, FEATURE_9, FEATURE_10, });
		TERMINAL_18.addFollower(TERMINAL_4, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_3, FEATURE_4, FEATURE_0, FEATURE_9, FEATURE_10, });
		TERMINAL_18.addFollower(TERMINAL_5, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_4, FEATURE_0, FEATURE_9, FEATURE_10, });
		TERMINAL_18.addFollower(TERMINAL_6, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_4, FEATURE_0, FEATURE_9, FEATURE_10, });
		TERMINAL_18.addFollower(TERMINAL_7, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_4, FEATURE_0, FEATURE_9, FEATURE_10, });
		TERMINAL_18.addFollower(TERMINAL_8, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_9, FEATURE_10, });
		TERMINAL_18.addFollower(TERMINAL_9, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_5, FEATURE_6, FEATURE_7, FEATURE_8, FEATURE_9, FEATURE_10, });
		TERMINAL_18.addFollower(TERMINAL_10, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, FEATURE_7, FEATURE_8, FEATURE_9, FEATURE_10, });
		TERMINAL_18.addFollower(TERMINAL_11, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_8, FEATURE_9, FEATURE_10, });
		TERMINAL_19.addFollower(TERMINAL_21, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_10, });
		TERMINAL_19.addFollower(TERMINAL_3, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, FEATURE_9, FEATURE_10, });
		TERMINAL_19.addFollower(TERMINAL_4, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_3, FEATURE_4, FEATURE_0, FEATURE_9, FEATURE_10, });
		TERMINAL_19.addFollower(TERMINAL_5, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_4, FEATURE_0, FEATURE_9, FEATURE_10, });
		TERMINAL_19.addFollower(TERMINAL_6, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_4, FEATURE_0, FEATURE_9, FEATURE_10, });
		TERMINAL_19.addFollower(TERMINAL_7, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_4, FEATURE_0, FEATURE_9, FEATURE_10, });
		TERMINAL_19.addFollower(TERMINAL_8, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_9, FEATURE_10, });
		TERMINAL_19.addFollower(TERMINAL_9, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_5, FEATURE_6, FEATURE_7, FEATURE_8, FEATURE_9, FEATURE_10, });
		TERMINAL_19.addFollower(TERMINAL_10, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, FEATURE_7, FEATURE_8, FEATURE_9, FEATURE_10, });
		TERMINAL_19.addFollower(TERMINAL_11, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_8, FEATURE_9, FEATURE_10, });
		TERMINAL_20.addFollower(TERMINAL_21, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_10, });
		TERMINAL_20.addFollower(TERMINAL_3, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, FEATURE_9, FEATURE_10, });
		TERMINAL_20.addFollower(TERMINAL_4, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_3, FEATURE_4, FEATURE_0, FEATURE_9, FEATURE_10, });
		TERMINAL_20.addFollower(TERMINAL_5, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_4, FEATURE_0, FEATURE_9, FEATURE_10, });
		TERMINAL_20.addFollower(TERMINAL_6, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_4, FEATURE_0, FEATURE_9, FEATURE_10, });
		TERMINAL_20.addFollower(TERMINAL_7, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_4, FEATURE_0, FEATURE_9, FEATURE_10, });
		TERMINAL_20.addFollower(TERMINAL_8, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_9, FEATURE_10, });
		TERMINAL_20.addFollower(TERMINAL_9, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_5, FEATURE_6, FEATURE_7, FEATURE_8, FEATURE_9, FEATURE_10, });
		TERMINAL_20.addFollower(TERMINAL_10, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, FEATURE_7, FEATURE_8, FEATURE_9, FEATURE_10, });
		TERMINAL_20.addFollower(TERMINAL_11, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_8, FEATURE_9, FEATURE_10, });
		TERMINAL_8.addFollower(TERMINAL_21, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_11, });
		TERMINAL_8.addFollower(TERMINAL_3, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, FEATURE_9, FEATURE_11, });
		TERMINAL_8.addFollower(TERMINAL_4, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_3, FEATURE_4, FEATURE_0, FEATURE_9, FEATURE_11, });
		TERMINAL_8.addFollower(TERMINAL_5, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_4, FEATURE_0, FEATURE_9, FEATURE_11, });
		TERMINAL_8.addFollower(TERMINAL_6, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_4, FEATURE_0, FEATURE_9, FEATURE_11, });
		TERMINAL_8.addFollower(TERMINAL_7, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_4, FEATURE_0, FEATURE_9, FEATURE_11, });
		TERMINAL_8.addFollower(TERMINAL_8, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_9, FEATURE_11, });
		TERMINAL_8.addFollower(TERMINAL_9, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_5, FEATURE_6, FEATURE_7, FEATURE_8, FEATURE_9, FEATURE_11, });
		TERMINAL_8.addFollower(TERMINAL_10, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, FEATURE_7, FEATURE_8, FEATURE_9, FEATURE_11, });
		TERMINAL_8.addFollower(TERMINAL_11, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_8, FEATURE_9, FEATURE_11, });
		TERMINAL_23.addFollower(TERMINAL_4, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_3, FEATURE_5, FEATURE_6, FEATURE_7, FEATURE_12, });
		TERMINAL_23.addFollower(TERMINAL_9, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_5, FEATURE_6, FEATURE_7, FEATURE_12, });
		TERMINAL_23.addFollower(TERMINAL_10, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, FEATURE_7, FEATURE_12, });
		TERMINAL_23.addFollower(TERMINAL_11, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_12, });
		TERMINAL_24.addFollower(TERMINAL_4, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_3, FEATURE_5, FEATURE_6, FEATURE_7, FEATURE_12, });
		TERMINAL_24.addFollower(TERMINAL_9, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_5, FEATURE_6, FEATURE_7, FEATURE_12, });
		TERMINAL_24.addFollower(TERMINAL_10, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, FEATURE_7, FEATURE_12, });
		TERMINAL_24.addFollower(TERMINAL_11, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_12, });
		TERMINAL_25.addFollower(TERMINAL_4, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_3, FEATURE_5, FEATURE_6, FEATURE_7, FEATURE_12, });
		TERMINAL_25.addFollower(TERMINAL_9, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_5, FEATURE_6, FEATURE_7, FEATURE_12, });
		TERMINAL_25.addFollower(TERMINAL_10, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, FEATURE_7, FEATURE_12, });
		TERMINAL_25.addFollower(TERMINAL_11, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_12, });
		TERMINAL_26.addFollower(TERMINAL_4, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_3, FEATURE_5, FEATURE_6, FEATURE_7, FEATURE_12, });
		TERMINAL_26.addFollower(TERMINAL_9, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_5, FEATURE_6, FEATURE_7, FEATURE_12, });
		TERMINAL_26.addFollower(TERMINAL_10, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, FEATURE_7, FEATURE_12, });
		TERMINAL_26.addFollower(TERMINAL_11, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_12, });
		TERMINAL_35.addFollower(TERMINAL_3, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, FEATURE_1, FEATURE_13, });
		TERMINAL_35.addFollower(TERMINAL_4, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_3, FEATURE_4, FEATURE_0, FEATURE_1, FEATURE_13, });
		TERMINAL_35.addFollower(TERMINAL_5, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_4, FEATURE_0, FEATURE_1, FEATURE_13, });
		TERMINAL_35.addFollower(TERMINAL_6, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_4, FEATURE_0, FEATURE_1, FEATURE_13, });
		TERMINAL_35.addFollower(TERMINAL_7, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_4, FEATURE_0, FEATURE_1, FEATURE_13, });
		TERMINAL_35.addFollower(TERMINAL_8, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_1, FEATURE_13, });
		TERMINAL_35.addFollower(TERMINAL_9, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_5, FEATURE_6, FEATURE_7, FEATURE_8, FEATURE_1, FEATURE_13, });
		TERMINAL_35.addFollower(TERMINAL_10, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, FEATURE_7, FEATURE_8, FEATURE_1, FEATURE_13, });
		TERMINAL_35.addFollower(TERMINAL_11, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_8, FEATURE_1, FEATURE_13, });
		TERMINAL_35.addFollower(TERMINAL_12, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_13, });
		TERMINAL_14.addFollower(TERMINAL_13, EMPTY_FEATURE_ARRAY);
		TERMINAL_14.addFollower(TERMINAL_14, EMPTY_FEATURE_ARRAY);
		TERMINAL_14.addFollower(TERMINAL_16, EMPTY_FEATURE_ARRAY);
		TERMINAL_14.addFollower(TERMINAL_22, EMPTY_FEATURE_ARRAY);
		TERMINAL_14.addFollower(TERMINAL_23, EMPTY_FEATURE_ARRAY);
		TERMINAL_14.addFollower(TERMINAL_24, EMPTY_FEATURE_ARRAY);
		TERMINAL_14.addFollower(TERMINAL_25, EMPTY_FEATURE_ARRAY);
		TERMINAL_14.addFollower(TERMINAL_26, EMPTY_FEATURE_ARRAY);
		TERMINAL_14.addFollower(TERMINAL_28, EMPTY_FEATURE_ARRAY);
		TERMINAL_14.addFollower(TERMINAL_29, EMPTY_FEATURE_ARRAY);
		TERMINAL_14.addFollower(TERMINAL_30, EMPTY_FEATURE_ARRAY);
		TERMINAL_14.addFollower(TERMINAL_31, EMPTY_FEATURE_ARRAY);
		TERMINAL_14.addFollower(TERMINAL_32, EMPTY_FEATURE_ARRAY);
		TERMINAL_14.addFollower(TERMINAL_33, EMPTY_FEATURE_ARRAY);
		TERMINAL_5.addFollower(TERMINAL_4, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_3, FEATURE_14, });
		TERMINAL_6.addFollower(TERMINAL_4, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_3, FEATURE_14, });
		TERMINAL_28.addFollower(TERMINAL_4, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_3, FEATURE_5, FEATURE_6, FEATURE_7, FEATURE_15, });
		TERMINAL_28.addFollower(TERMINAL_9, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_5, FEATURE_6, FEATURE_7, FEATURE_15, });
		TERMINAL_28.addFollower(TERMINAL_10, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, FEATURE_7, FEATURE_15, });
		TERMINAL_28.addFollower(TERMINAL_11, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_15, });
		TERMINAL_29.addFollower(TERMINAL_4, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_3, FEATURE_5, FEATURE_6, FEATURE_7, FEATURE_15, });
		TERMINAL_29.addFollower(TERMINAL_9, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_5, FEATURE_6, FEATURE_7, FEATURE_15, });
		TERMINAL_29.addFollower(TERMINAL_10, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, FEATURE_7, FEATURE_15, });
		TERMINAL_29.addFollower(TERMINAL_11, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_15, });
		TERMINAL_30.addFollower(TERMINAL_4, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_3, FEATURE_5, FEATURE_6, FEATURE_7, FEATURE_15, });
		TERMINAL_30.addFollower(TERMINAL_9, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_5, FEATURE_6, FEATURE_7, FEATURE_15, });
		TERMINAL_30.addFollower(TERMINAL_10, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, FEATURE_7, FEATURE_15, });
		TERMINAL_30.addFollower(TERMINAL_11, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_15, });
		TERMINAL_31.addFollower(TERMINAL_4, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_3, FEATURE_5, FEATURE_6, FEATURE_7, FEATURE_15, });
		TERMINAL_31.addFollower(TERMINAL_9, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_5, FEATURE_6, FEATURE_7, FEATURE_15, });
		TERMINAL_31.addFollower(TERMINAL_10, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, FEATURE_7, FEATURE_15, });
		TERMINAL_31.addFollower(TERMINAL_11, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_15, });
		TERMINAL_32.addFollower(TERMINAL_4, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_3, FEATURE_5, FEATURE_6, FEATURE_7, FEATURE_15, });
		TERMINAL_32.addFollower(TERMINAL_9, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_5, FEATURE_6, FEATURE_7, FEATURE_15, });
		TERMINAL_32.addFollower(TERMINAL_10, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, FEATURE_7, FEATURE_15, });
		TERMINAL_32.addFollower(TERMINAL_11, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_15, });
		TERMINAL_33.addFollower(TERMINAL_4, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_3, FEATURE_5, FEATURE_6, FEATURE_7, FEATURE_15, });
		TERMINAL_33.addFollower(TERMINAL_9, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_5, FEATURE_6, FEATURE_7, FEATURE_15, });
		TERMINAL_33.addFollower(TERMINAL_10, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, FEATURE_7, FEATURE_15, });
		TERMINAL_33.addFollower(TERMINAL_11, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_15, });
		TERMINAL_7.addFollower(TERMINAL_13, EMPTY_FEATURE_ARRAY);
		TERMINAL_7.addFollower(TERMINAL_14, EMPTY_FEATURE_ARRAY);
		TERMINAL_7.addFollower(TERMINAL_16, EMPTY_FEATURE_ARRAY);
		TERMINAL_7.addFollower(TERMINAL_22, EMPTY_FEATURE_ARRAY);
		TERMINAL_4.addFollower(TERMINAL_23, EMPTY_FEATURE_ARRAY);
		TERMINAL_4.addFollower(TERMINAL_24, EMPTY_FEATURE_ARRAY);
		TERMINAL_4.addFollower(TERMINAL_25, EMPTY_FEATURE_ARRAY);
		TERMINAL_4.addFollower(TERMINAL_26, EMPTY_FEATURE_ARRAY);
		TERMINAL_4.addFollower(TERMINAL_28, EMPTY_FEATURE_ARRAY);
		TERMINAL_4.addFollower(TERMINAL_29, EMPTY_FEATURE_ARRAY);
		TERMINAL_4.addFollower(TERMINAL_30, EMPTY_FEATURE_ARRAY);
		TERMINAL_4.addFollower(TERMINAL_31, EMPTY_FEATURE_ARRAY);
		TERMINAL_4.addFollower(TERMINAL_32, EMPTY_FEATURE_ARRAY);
		TERMINAL_4.addFollower(TERMINAL_33, EMPTY_FEATURE_ARRAY);
		TERMINAL_4.addFollower(TERMINAL_35, EMPTY_FEATURE_ARRAY);
		TERMINAL_9.addFollower(TERMINAL_23, EMPTY_FEATURE_ARRAY);
		TERMINAL_9.addFollower(TERMINAL_24, EMPTY_FEATURE_ARRAY);
		TERMINAL_9.addFollower(TERMINAL_25, EMPTY_FEATURE_ARRAY);
		TERMINAL_9.addFollower(TERMINAL_26, EMPTY_FEATURE_ARRAY);
		TERMINAL_9.addFollower(TERMINAL_28, EMPTY_FEATURE_ARRAY);
		TERMINAL_9.addFollower(TERMINAL_29, EMPTY_FEATURE_ARRAY);
		TERMINAL_9.addFollower(TERMINAL_30, EMPTY_FEATURE_ARRAY);
		TERMINAL_9.addFollower(TERMINAL_31, EMPTY_FEATURE_ARRAY);
		TERMINAL_9.addFollower(TERMINAL_32, EMPTY_FEATURE_ARRAY);
		TERMINAL_9.addFollower(TERMINAL_33, EMPTY_FEATURE_ARRAY);
	}
	// wire the terminals
	static {
		wire0();
	}
}
