/**
 * <copyright>
 * </copyright>
 *
 * 
 */
package syntax.resource.constraint.grammar;

/**
 * This class provides the follow sets for all terminals of the grammar. These
 * sets are used during code completion.
 */
public class ConstraintFollowSetProvider {
	
	public final static syntax.resource.constraint.IConstraintExpectedElement TERMINAL_0 = new syntax.resource.constraint.mopp.ConstraintExpectedCsString(syntax.resource.constraint.grammar.ConstraintGrammarInformationProvider.CONSTRAINT_0_0_0_0);
	public final static syntax.resource.constraint.IConstraintExpectedElement TERMINAL_1 = new syntax.resource.constraint.mopp.ConstraintExpectedStructuralFeature(syntax.resource.constraint.grammar.ConstraintGrammarInformationProvider.CONSTRAINT_0_0_0_1);
	public final static syntax.resource.constraint.IConstraintExpectedElement TERMINAL_2 = new syntax.resource.constraint.mopp.ConstraintExpectedCsString(syntax.resource.constraint.grammar.ConstraintGrammarInformationProvider.CONSTRAINT_0_0_0_2);
	public final static syntax.resource.constraint.IConstraintExpectedElement TERMINAL_3 = new syntax.resource.constraint.mopp.ConstraintExpectedCsString(syntax.resource.constraint.grammar.ConstraintGrammarInformationProvider.CONSTRAINT_2_0_0_0);
	public final static syntax.resource.constraint.IConstraintExpectedElement TERMINAL_4 = new syntax.resource.constraint.mopp.ConstraintExpectedStructuralFeature(syntax.resource.constraint.grammar.ConstraintGrammarInformationProvider.CONSTRAINT_24_0_0_0);
	public final static syntax.resource.constraint.IConstraintExpectedElement TERMINAL_5 = new syntax.resource.constraint.mopp.ConstraintExpectedStructuralFeature(syntax.resource.constraint.grammar.ConstraintGrammarInformationProvider.CONSTRAINT_25_0_0_0);
	public final static syntax.resource.constraint.IConstraintExpectedElement TERMINAL_6 = new syntax.resource.constraint.mopp.ConstraintExpectedCsString(syntax.resource.constraint.grammar.ConstraintGrammarInformationProvider.CONSTRAINT_16_0_0_0);
	public final static syntax.resource.constraint.IConstraintExpectedElement TERMINAL_7 = new syntax.resource.constraint.mopp.ConstraintExpectedCsString(syntax.resource.constraint.grammar.ConstraintGrammarInformationProvider.CONSTRAINT_17_0_0_0);
	public final static syntax.resource.constraint.IConstraintExpectedElement TERMINAL_8 = new syntax.resource.constraint.mopp.ConstraintExpectedCsString(syntax.resource.constraint.grammar.ConstraintGrammarInformationProvider.CONSTRAINT_10_0_0_0);
	public final static syntax.resource.constraint.IConstraintExpectedElement TERMINAL_9 = new syntax.resource.constraint.mopp.ConstraintExpectedStructuralFeature(syntax.resource.constraint.grammar.ConstraintGrammarInformationProvider.CONSTRAINT_26_0_0_0);
	public final static syntax.resource.constraint.IConstraintExpectedElement TERMINAL_10 = new syntax.resource.constraint.mopp.ConstraintExpectedCsString(syntax.resource.constraint.grammar.ConstraintGrammarInformationProvider.CONSTRAINT_4_0_1_0);
	public final static syntax.resource.constraint.IConstraintExpectedElement TERMINAL_11 = new syntax.resource.constraint.mopp.ConstraintExpectedCsString(syntax.resource.constraint.grammar.ConstraintGrammarInformationProvider.CONSTRAINT_5_0_1_0);
	public final static syntax.resource.constraint.IConstraintExpectedElement TERMINAL_12 = new syntax.resource.constraint.mopp.ConstraintExpectedCsString(syntax.resource.constraint.grammar.ConstraintGrammarInformationProvider.CONSTRAINT_1_0_1_0);
	public final static syntax.resource.constraint.IConstraintExpectedElement TERMINAL_13 = new syntax.resource.constraint.mopp.ConstraintExpectedCsString(syntax.resource.constraint.grammar.ConstraintGrammarInformationProvider.CONSTRAINT_0_0_0_3_0_0_1);
	public final static syntax.resource.constraint.IConstraintExpectedElement TERMINAL_14 = new syntax.resource.constraint.mopp.ConstraintExpectedCsString(syntax.resource.constraint.grammar.ConstraintGrammarInformationProvider.CONSTRAINT_15_0_0_3);
	public final static syntax.resource.constraint.IConstraintExpectedElement TERMINAL_15 = new syntax.resource.constraint.mopp.ConstraintExpectedCsString(syntax.resource.constraint.grammar.ConstraintGrammarInformationProvider.CONSTRAINT_1_0_1_2);
	public final static syntax.resource.constraint.IConstraintExpectedElement TERMINAL_16 = new syntax.resource.constraint.mopp.ConstraintExpectedCsString(syntax.resource.constraint.grammar.ConstraintGrammarInformationProvider.CONSTRAINT_2_0_0_2);
	public final static syntax.resource.constraint.IConstraintExpectedElement TERMINAL_17 = new syntax.resource.constraint.mopp.ConstraintExpectedCsString(syntax.resource.constraint.grammar.ConstraintGrammarInformationProvider.CONSTRAINT_6_0_0_1);
	public final static syntax.resource.constraint.IConstraintExpectedElement TERMINAL_18 = new syntax.resource.constraint.mopp.ConstraintExpectedCsString(syntax.resource.constraint.grammar.ConstraintGrammarInformationProvider.CONSTRAINT_7_0_0_1);
	public final static syntax.resource.constraint.IConstraintExpectedElement TERMINAL_19 = new syntax.resource.constraint.mopp.ConstraintExpectedCsString(syntax.resource.constraint.grammar.ConstraintGrammarInformationProvider.CONSTRAINT_8_0_0_1);
	public final static syntax.resource.constraint.IConstraintExpectedElement TERMINAL_20 = new syntax.resource.constraint.mopp.ConstraintExpectedCsString(syntax.resource.constraint.grammar.ConstraintGrammarInformationProvider.CONSTRAINT_9_0_0_1);
	public final static syntax.resource.constraint.IConstraintExpectedElement TERMINAL_21 = new syntax.resource.constraint.mopp.ConstraintExpectedCsString(syntax.resource.constraint.grammar.ConstraintGrammarInformationProvider.CONSTRAINT_3_0_0_0);
	public final static syntax.resource.constraint.IConstraintExpectedElement TERMINAL_22 = new syntax.resource.constraint.mopp.ConstraintExpectedCsString(syntax.resource.constraint.grammar.ConstraintGrammarInformationProvider.CONSTRAINT_3_0_0_2);
	public final static syntax.resource.constraint.IConstraintExpectedElement TERMINAL_23 = new syntax.resource.constraint.mopp.ConstraintExpectedCsString(syntax.resource.constraint.grammar.ConstraintGrammarInformationProvider.CONSTRAINT_11_0_0_1);
	public final static syntax.resource.constraint.IConstraintExpectedElement TERMINAL_24 = new syntax.resource.constraint.mopp.ConstraintExpectedCsString(syntax.resource.constraint.grammar.ConstraintGrammarInformationProvider.CONSTRAINT_12_0_0_1);
	public final static syntax.resource.constraint.IConstraintExpectedElement TERMINAL_25 = new syntax.resource.constraint.mopp.ConstraintExpectedCsString(syntax.resource.constraint.grammar.ConstraintGrammarInformationProvider.CONSTRAINT_13_0_0_1);
	public final static syntax.resource.constraint.IConstraintExpectedElement TERMINAL_26 = new syntax.resource.constraint.mopp.ConstraintExpectedCsString(syntax.resource.constraint.grammar.ConstraintGrammarInformationProvider.CONSTRAINT_14_0_0_1);
	public final static syntax.resource.constraint.IConstraintExpectedElement TERMINAL_27 = new syntax.resource.constraint.mopp.ConstraintExpectedCsString(syntax.resource.constraint.grammar.ConstraintGrammarInformationProvider.CONSTRAINT_4_0_1_2);
	public final static syntax.resource.constraint.IConstraintExpectedElement TERMINAL_28 = new syntax.resource.constraint.mopp.ConstraintExpectedCsString(syntax.resource.constraint.grammar.ConstraintGrammarInformationProvider.CONSTRAINT_18_0_0_1);
	public final static syntax.resource.constraint.IConstraintExpectedElement TERMINAL_29 = new syntax.resource.constraint.mopp.ConstraintExpectedCsString(syntax.resource.constraint.grammar.ConstraintGrammarInformationProvider.CONSTRAINT_19_0_0_1);
	public final static syntax.resource.constraint.IConstraintExpectedElement TERMINAL_30 = new syntax.resource.constraint.mopp.ConstraintExpectedCsString(syntax.resource.constraint.grammar.ConstraintGrammarInformationProvider.CONSTRAINT_20_0_0_1);
	public final static syntax.resource.constraint.IConstraintExpectedElement TERMINAL_31 = new syntax.resource.constraint.mopp.ConstraintExpectedCsString(syntax.resource.constraint.grammar.ConstraintGrammarInformationProvider.CONSTRAINT_21_0_0_1);
	public final static syntax.resource.constraint.IConstraintExpectedElement TERMINAL_32 = new syntax.resource.constraint.mopp.ConstraintExpectedCsString(syntax.resource.constraint.grammar.ConstraintGrammarInformationProvider.CONSTRAINT_22_0_0_1);
	public final static syntax.resource.constraint.IConstraintExpectedElement TERMINAL_33 = new syntax.resource.constraint.mopp.ConstraintExpectedCsString(syntax.resource.constraint.grammar.ConstraintGrammarInformationProvider.CONSTRAINT_23_0_0_1);
	public final static syntax.resource.constraint.IConstraintExpectedElement TERMINAL_34 = new syntax.resource.constraint.mopp.ConstraintExpectedCsString(syntax.resource.constraint.grammar.ConstraintGrammarInformationProvider.CONSTRAINT_5_0_1_2);
	public final static syntax.resource.constraint.IConstraintExpectedElement TERMINAL_35 = new syntax.resource.constraint.mopp.ConstraintExpectedCsString(syntax.resource.constraint.grammar.ConstraintGrammarInformationProvider.CONSTRAINT_15_0_0_1);
	
	public final static org.eclipse.emf.ecore.EStructuralFeature FEATURE_0 = syntax.SyntaxPackage.eINSTANCE.getBinaryOp().getEStructuralFeature(syntax.SyntaxPackage.BINARY_OP__BINARY_OP1);
	public final static org.eclipse.emf.ecore.EStructuralFeature FEATURE_1 = syntax.SyntaxPackage.eINSTANCE.getConstraint().getEStructuralFeature(syntax.SyntaxPackage.CONSTRAINT__OPERATORS);
	public final static org.eclipse.emf.ecore.EStructuralFeature FEATURE_2 = syntax.SyntaxPackage.eINSTANCE.getModel().getEStructuralFeature(syntax.SyntaxPackage.MODEL__CONSTRAINTS);
	public final static org.eclipse.emf.ecore.EStructuralFeature FEATURE_3 = syntax.SyntaxPackage.eINSTANCE.getContext().getEStructuralFeature(syntax.SyntaxPackage.CONTEXT__CONTEXT_OP1);
	public final static org.eclipse.emf.ecore.EStructuralFeature FEATURE_4 = syntax.SyntaxPackage.eINSTANCE.getBoolPriorityOperand1().getEStructuralFeature(syntax.SyntaxPackage.BOOL_PRIORITY_OPERAND1__BOOL_PRIORITY_OP1);
	public final static org.eclipse.emf.ecore.EStructuralFeature FEATURE_5 = syntax.SyntaxPackage.eINSTANCE.getNumPriorityOperand1().getEStructuralFeature(syntax.SyntaxPackage.NUM_PRIORITY_OPERAND1__NUM_PRIORITY_OP1);
	public final static org.eclipse.emf.ecore.EStructuralFeature FEATURE_6 = syntax.SyntaxPackage.eINSTANCE.getNumOperator().getEStructuralFeature(syntax.SyntaxPackage.NUM_OPERATOR__NUM_OP1);
	public final static org.eclipse.emf.ecore.EStructuralFeature FEATURE_7 = syntax.SyntaxPackage.eINSTANCE.getComparison().getEStructuralFeature(syntax.SyntaxPackage.COMPARISON__COMP_OP1);
	public final static org.eclipse.emf.ecore.EStructuralFeature FEATURE_8 = syntax.SyntaxPackage.eINSTANCE.getNumPriorityOperand2().getEStructuralFeature(syntax.SyntaxPackage.NUM_PRIORITY_OPERAND2__NUM_PRIORITY_OP2);
	public final static org.eclipse.emf.ecore.EStructuralFeature FEATURE_9 = syntax.SyntaxPackage.eINSTANCE.getBoolPriorityOperand2().getEStructuralFeature(syntax.SyntaxPackage.BOOL_PRIORITY_OPERAND2__BOOL_PRIORITY_OP2);
	public final static org.eclipse.emf.ecore.EStructuralFeature FEATURE_10 = syntax.SyntaxPackage.eINSTANCE.getBinaryOp().getEStructuralFeature(syntax.SyntaxPackage.BINARY_OP__BINARY_OP2);
	public final static org.eclipse.emf.ecore.EStructuralFeature FEATURE_11 = syntax.SyntaxPackage.eINSTANCE.getUnaryOp().getEStructuralFeature(syntax.SyntaxPackage.UNARY_OP__UNARY_OP);
	public final static org.eclipse.emf.ecore.EStructuralFeature FEATURE_12 = syntax.SyntaxPackage.eINSTANCE.getNumOperator().getEStructuralFeature(syntax.SyntaxPackage.NUM_OPERATOR__NUM_OP2);
	public final static org.eclipse.emf.ecore.EStructuralFeature FEATURE_13 = syntax.SyntaxPackage.eINSTANCE.getContext().getEStructuralFeature(syntax.SyntaxPackage.CONTEXT__CONTEXT_OP2);
	public final static org.eclipse.emf.ecore.EStructuralFeature FEATURE_14 = syntax.SyntaxPackage.eINSTANCE.getSelection().getEStructuralFeature(syntax.SyntaxPackage.SELECTION__SELECTION_OP);
	public final static org.eclipse.emf.ecore.EStructuralFeature FEATURE_15 = syntax.SyntaxPackage.eINSTANCE.getComparison().getEStructuralFeature(syntax.SyntaxPackage.COMPARISON__COMP_OP2);
	
	public final static org.eclipse.emf.ecore.EStructuralFeature[] EMPTY_FEATURE_ARRAY = new org.eclipse.emf.ecore.EStructuralFeature[0];
	
	public static void wire0() {
		TERMINAL_0.addFollower(TERMINAL_1, EMPTY_FEATURE_ARRAY);
		TERMINAL_1.addFollower(TERMINAL_2, EMPTY_FEATURE_ARRAY);
		TERMINAL_2.addFollower(TERMINAL_3, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, FEATURE_1, FEATURE_2, });
		TERMINAL_2.addFollower(TERMINAL_4, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_3, FEATURE_4, FEATURE_0, FEATURE_1, FEATURE_2, });
		TERMINAL_2.addFollower(TERMINAL_5, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_3, FEATURE_4, FEATURE_0, FEATURE_1, FEATURE_2, });
		TERMINAL_2.addFollower(TERMINAL_6, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_4, FEATURE_0, FEATURE_1, FEATURE_2, });
		TERMINAL_2.addFollower(TERMINAL_7, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_4, FEATURE_0, FEATURE_1, FEATURE_2, });
		TERMINAL_2.addFollower(TERMINAL_8, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_1, FEATURE_2, });
		TERMINAL_2.addFollower(TERMINAL_9, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_5, FEATURE_6, FEATURE_1, FEATURE_2, });
		TERMINAL_2.addFollower(TERMINAL_10, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, FEATURE_1, FEATURE_2, });
		TERMINAL_2.addFollower(TERMINAL_11, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_7, FEATURE_1, FEATURE_2, });
		TERMINAL_2.addFollower(TERMINAL_12, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_2, });
		TERMINAL_13.addFollower(TERMINAL_3, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, FEATURE_1, FEATURE_2, });
		TERMINAL_13.addFollower(TERMINAL_4, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_3, FEATURE_4, FEATURE_0, FEATURE_1, FEATURE_2, });
		TERMINAL_13.addFollower(TERMINAL_5, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_3, FEATURE_4, FEATURE_0, FEATURE_1, FEATURE_2, });
		TERMINAL_13.addFollower(TERMINAL_6, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_4, FEATURE_0, FEATURE_1, FEATURE_2, });
		TERMINAL_13.addFollower(TERMINAL_7, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_4, FEATURE_0, FEATURE_1, FEATURE_2, });
		TERMINAL_13.addFollower(TERMINAL_8, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_1, FEATURE_2, });
		TERMINAL_13.addFollower(TERMINAL_9, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_5, FEATURE_6, FEATURE_1, FEATURE_2, });
		TERMINAL_13.addFollower(TERMINAL_10, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, FEATURE_1, FEATURE_2, });
		TERMINAL_13.addFollower(TERMINAL_11, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_7, FEATURE_1, FEATURE_2, });
		TERMINAL_13.addFollower(TERMINAL_12, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_2, });
		TERMINAL_12.addFollower(TERMINAL_3, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, FEATURE_1, });
		TERMINAL_12.addFollower(TERMINAL_4, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_3, FEATURE_4, FEATURE_0, FEATURE_1, });
		TERMINAL_12.addFollower(TERMINAL_5, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_3, FEATURE_4, FEATURE_0, FEATURE_1, });
		TERMINAL_12.addFollower(TERMINAL_6, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_4, FEATURE_0, FEATURE_1, });
		TERMINAL_12.addFollower(TERMINAL_7, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_4, FEATURE_0, FEATURE_1, });
		TERMINAL_12.addFollower(TERMINAL_8, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_1, });
		TERMINAL_12.addFollower(TERMINAL_9, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_5, FEATURE_6, FEATURE_1, });
		TERMINAL_12.addFollower(TERMINAL_10, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, FEATURE_1, });
		TERMINAL_12.addFollower(TERMINAL_11, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_7, FEATURE_1, });
		TERMINAL_15.addFollower(TERMINAL_13, EMPTY_FEATURE_ARRAY);
		TERMINAL_15.addFollower(TERMINAL_14, EMPTY_FEATURE_ARRAY);
		TERMINAL_3.addFollower(TERMINAL_3, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, FEATURE_4, });
		TERMINAL_3.addFollower(TERMINAL_4, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_3, FEATURE_4, FEATURE_0, FEATURE_4, });
		TERMINAL_3.addFollower(TERMINAL_5, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_3, FEATURE_4, FEATURE_0, FEATURE_4, });
		TERMINAL_3.addFollower(TERMINAL_6, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_4, FEATURE_0, FEATURE_4, });
		TERMINAL_3.addFollower(TERMINAL_7, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_4, FEATURE_0, FEATURE_4, });
		TERMINAL_3.addFollower(TERMINAL_8, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_4, });
		TERMINAL_3.addFollower(TERMINAL_9, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_5, FEATURE_6, FEATURE_8, FEATURE_7, FEATURE_4, });
		TERMINAL_3.addFollower(TERMINAL_10, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, FEATURE_8, FEATURE_7, FEATURE_4, });
		TERMINAL_3.addFollower(TERMINAL_11, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_7, FEATURE_4, });
		TERMINAL_16.addFollower(TERMINAL_17, EMPTY_FEATURE_ARRAY);
		TERMINAL_16.addFollower(TERMINAL_18, EMPTY_FEATURE_ARRAY);
		TERMINAL_16.addFollower(TERMINAL_19, EMPTY_FEATURE_ARRAY);
		TERMINAL_16.addFollower(TERMINAL_20, EMPTY_FEATURE_ARRAY);
		TERMINAL_21.addFollower(TERMINAL_3, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, FEATURE_9, });
		TERMINAL_21.addFollower(TERMINAL_4, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_3, FEATURE_4, FEATURE_0, FEATURE_9, });
		TERMINAL_21.addFollower(TERMINAL_5, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_3, FEATURE_4, FEATURE_0, FEATURE_9, });
		TERMINAL_21.addFollower(TERMINAL_6, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_4, FEATURE_0, FEATURE_9, });
		TERMINAL_21.addFollower(TERMINAL_7, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_4, FEATURE_0, FEATURE_9, });
		TERMINAL_21.addFollower(TERMINAL_8, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_9, });
		TERMINAL_21.addFollower(TERMINAL_9, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_5, FEATURE_6, FEATURE_8, FEATURE_7, FEATURE_9, });
		TERMINAL_21.addFollower(TERMINAL_10, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, FEATURE_8, FEATURE_7, FEATURE_9, });
		TERMINAL_21.addFollower(TERMINAL_11, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_7, FEATURE_9, });
		TERMINAL_22.addFollower(TERMINAL_13, EMPTY_FEATURE_ARRAY);
		TERMINAL_22.addFollower(TERMINAL_14, EMPTY_FEATURE_ARRAY);
		TERMINAL_22.addFollower(TERMINAL_16, EMPTY_FEATURE_ARRAY);
		TERMINAL_22.addFollower(TERMINAL_22, EMPTY_FEATURE_ARRAY);
		TERMINAL_10.addFollower(TERMINAL_4, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_3, FEATURE_5, FEATURE_6, FEATURE_5, });
		TERMINAL_10.addFollower(TERMINAL_5, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_3, FEATURE_5, FEATURE_6, FEATURE_5, });
		TERMINAL_10.addFollower(TERMINAL_9, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_5, FEATURE_6, FEATURE_5, });
		TERMINAL_10.addFollower(TERMINAL_10, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, FEATURE_5, });
		TERMINAL_27.addFollower(TERMINAL_23, EMPTY_FEATURE_ARRAY);
		TERMINAL_27.addFollower(TERMINAL_24, EMPTY_FEATURE_ARRAY);
		TERMINAL_27.addFollower(TERMINAL_25, EMPTY_FEATURE_ARRAY);
		TERMINAL_27.addFollower(TERMINAL_26, EMPTY_FEATURE_ARRAY);
		TERMINAL_11.addFollower(TERMINAL_4, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_3, FEATURE_5, FEATURE_6, FEATURE_8, });
		TERMINAL_11.addFollower(TERMINAL_5, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_3, FEATURE_5, FEATURE_6, FEATURE_8, });
		TERMINAL_11.addFollower(TERMINAL_9, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_5, FEATURE_6, FEATURE_8, });
		TERMINAL_11.addFollower(TERMINAL_10, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, FEATURE_8, });
		TERMINAL_34.addFollower(TERMINAL_13, EMPTY_FEATURE_ARRAY);
		TERMINAL_34.addFollower(TERMINAL_14, EMPTY_FEATURE_ARRAY);
		TERMINAL_34.addFollower(TERMINAL_27, EMPTY_FEATURE_ARRAY);
		TERMINAL_34.addFollower(TERMINAL_28, EMPTY_FEATURE_ARRAY);
		TERMINAL_34.addFollower(TERMINAL_29, EMPTY_FEATURE_ARRAY);
		TERMINAL_34.addFollower(TERMINAL_30, EMPTY_FEATURE_ARRAY);
		TERMINAL_34.addFollower(TERMINAL_31, EMPTY_FEATURE_ARRAY);
		TERMINAL_34.addFollower(TERMINAL_32, EMPTY_FEATURE_ARRAY);
		TERMINAL_34.addFollower(TERMINAL_33, EMPTY_FEATURE_ARRAY);
		TERMINAL_17.addFollower(TERMINAL_21, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_10, });
		TERMINAL_17.addFollower(TERMINAL_3, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, FEATURE_9, FEATURE_10, });
		TERMINAL_17.addFollower(TERMINAL_4, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_3, FEATURE_4, FEATURE_0, FEATURE_9, FEATURE_10, });
		TERMINAL_17.addFollower(TERMINAL_5, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_3, FEATURE_4, FEATURE_0, FEATURE_9, FEATURE_10, });
		TERMINAL_17.addFollower(TERMINAL_6, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_4, FEATURE_0, FEATURE_9, FEATURE_10, });
		TERMINAL_17.addFollower(TERMINAL_7, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_4, FEATURE_0, FEATURE_9, FEATURE_10, });
		TERMINAL_17.addFollower(TERMINAL_8, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_9, FEATURE_10, });
		TERMINAL_17.addFollower(TERMINAL_9, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_5, FEATURE_6, FEATURE_8, FEATURE_7, FEATURE_9, FEATURE_10, });
		TERMINAL_17.addFollower(TERMINAL_10, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, FEATURE_8, FEATURE_7, FEATURE_9, FEATURE_10, });
		TERMINAL_17.addFollower(TERMINAL_11, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_7, FEATURE_9, FEATURE_10, });
		TERMINAL_18.addFollower(TERMINAL_21, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_10, });
		TERMINAL_18.addFollower(TERMINAL_3, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, FEATURE_9, FEATURE_10, });
		TERMINAL_18.addFollower(TERMINAL_4, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_3, FEATURE_4, FEATURE_0, FEATURE_9, FEATURE_10, });
		TERMINAL_18.addFollower(TERMINAL_5, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_3, FEATURE_4, FEATURE_0, FEATURE_9, FEATURE_10, });
		TERMINAL_18.addFollower(TERMINAL_6, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_4, FEATURE_0, FEATURE_9, FEATURE_10, });
		TERMINAL_18.addFollower(TERMINAL_7, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_4, FEATURE_0, FEATURE_9, FEATURE_10, });
		TERMINAL_18.addFollower(TERMINAL_8, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_9, FEATURE_10, });
		TERMINAL_18.addFollower(TERMINAL_9, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_5, FEATURE_6, FEATURE_8, FEATURE_7, FEATURE_9, FEATURE_10, });
		TERMINAL_18.addFollower(TERMINAL_10, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, FEATURE_8, FEATURE_7, FEATURE_9, FEATURE_10, });
		TERMINAL_18.addFollower(TERMINAL_11, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_7, FEATURE_9, FEATURE_10, });
		TERMINAL_19.addFollower(TERMINAL_21, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_10, });
		TERMINAL_19.addFollower(TERMINAL_3, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, FEATURE_9, FEATURE_10, });
		TERMINAL_19.addFollower(TERMINAL_4, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_3, FEATURE_4, FEATURE_0, FEATURE_9, FEATURE_10, });
		TERMINAL_19.addFollower(TERMINAL_5, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_3, FEATURE_4, FEATURE_0, FEATURE_9, FEATURE_10, });
		TERMINAL_19.addFollower(TERMINAL_6, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_4, FEATURE_0, FEATURE_9, FEATURE_10, });
		TERMINAL_19.addFollower(TERMINAL_7, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_4, FEATURE_0, FEATURE_9, FEATURE_10, });
		TERMINAL_19.addFollower(TERMINAL_8, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_9, FEATURE_10, });
		TERMINAL_19.addFollower(TERMINAL_9, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_5, FEATURE_6, FEATURE_8, FEATURE_7, FEATURE_9, FEATURE_10, });
		TERMINAL_19.addFollower(TERMINAL_10, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, FEATURE_8, FEATURE_7, FEATURE_9, FEATURE_10, });
		TERMINAL_19.addFollower(TERMINAL_11, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_7, FEATURE_9, FEATURE_10, });
		TERMINAL_20.addFollower(TERMINAL_21, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_10, });
		TERMINAL_20.addFollower(TERMINAL_3, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, FEATURE_9, FEATURE_10, });
		TERMINAL_20.addFollower(TERMINAL_4, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_3, FEATURE_4, FEATURE_0, FEATURE_9, FEATURE_10, });
		TERMINAL_20.addFollower(TERMINAL_5, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_3, FEATURE_4, FEATURE_0, FEATURE_9, FEATURE_10, });
		TERMINAL_20.addFollower(TERMINAL_6, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_4, FEATURE_0, FEATURE_9, FEATURE_10, });
		TERMINAL_20.addFollower(TERMINAL_7, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_4, FEATURE_0, FEATURE_9, FEATURE_10, });
		TERMINAL_20.addFollower(TERMINAL_8, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_9, FEATURE_10, });
		TERMINAL_20.addFollower(TERMINAL_9, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_5, FEATURE_6, FEATURE_8, FEATURE_7, FEATURE_9, FEATURE_10, });
		TERMINAL_20.addFollower(TERMINAL_10, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, FEATURE_8, FEATURE_7, FEATURE_9, FEATURE_10, });
		TERMINAL_20.addFollower(TERMINAL_11, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_7, FEATURE_9, FEATURE_10, });
		TERMINAL_8.addFollower(TERMINAL_21, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_11, });
		TERMINAL_8.addFollower(TERMINAL_3, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, FEATURE_9, FEATURE_11, });
		TERMINAL_8.addFollower(TERMINAL_4, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_3, FEATURE_4, FEATURE_0, FEATURE_9, FEATURE_11, });
		TERMINAL_8.addFollower(TERMINAL_5, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_3, FEATURE_4, FEATURE_0, FEATURE_9, FEATURE_11, });
		TERMINAL_8.addFollower(TERMINAL_6, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_4, FEATURE_0, FEATURE_9, FEATURE_11, });
		TERMINAL_8.addFollower(TERMINAL_7, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_4, FEATURE_0, FEATURE_9, FEATURE_11, });
		TERMINAL_8.addFollower(TERMINAL_8, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_9, FEATURE_11, });
		TERMINAL_8.addFollower(TERMINAL_9, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_5, FEATURE_6, FEATURE_8, FEATURE_7, FEATURE_9, FEATURE_11, });
		TERMINAL_8.addFollower(TERMINAL_10, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, FEATURE_8, FEATURE_7, FEATURE_9, FEATURE_11, });
		TERMINAL_8.addFollower(TERMINAL_11, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_7, FEATURE_9, FEATURE_11, });
		TERMINAL_23.addFollower(TERMINAL_4, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_3, FEATURE_5, FEATURE_6, FEATURE_8, FEATURE_12, });
		TERMINAL_23.addFollower(TERMINAL_5, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_3, FEATURE_5, FEATURE_6, FEATURE_8, FEATURE_12, });
		TERMINAL_23.addFollower(TERMINAL_9, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_5, FEATURE_6, FEATURE_8, FEATURE_12, });
		TERMINAL_23.addFollower(TERMINAL_10, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, FEATURE_8, FEATURE_12, });
		TERMINAL_23.addFollower(TERMINAL_11, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_12, });
		TERMINAL_24.addFollower(TERMINAL_4, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_3, FEATURE_5, FEATURE_6, FEATURE_8, FEATURE_12, });
		TERMINAL_24.addFollower(TERMINAL_5, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_3, FEATURE_5, FEATURE_6, FEATURE_8, FEATURE_12, });
		TERMINAL_24.addFollower(TERMINAL_9, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_5, FEATURE_6, FEATURE_8, FEATURE_12, });
		TERMINAL_24.addFollower(TERMINAL_10, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, FEATURE_8, FEATURE_12, });
		TERMINAL_24.addFollower(TERMINAL_11, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_12, });
		TERMINAL_25.addFollower(TERMINAL_4, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_3, FEATURE_5, FEATURE_6, FEATURE_8, FEATURE_12, });
		TERMINAL_25.addFollower(TERMINAL_5, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_3, FEATURE_5, FEATURE_6, FEATURE_8, FEATURE_12, });
		TERMINAL_25.addFollower(TERMINAL_9, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_5, FEATURE_6, FEATURE_8, FEATURE_12, });
		TERMINAL_25.addFollower(TERMINAL_10, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, FEATURE_8, FEATURE_12, });
		TERMINAL_25.addFollower(TERMINAL_11, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_12, });
		TERMINAL_26.addFollower(TERMINAL_4, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_3, FEATURE_5, FEATURE_6, FEATURE_8, FEATURE_12, });
		TERMINAL_26.addFollower(TERMINAL_5, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_3, FEATURE_5, FEATURE_6, FEATURE_8, FEATURE_12, });
		TERMINAL_26.addFollower(TERMINAL_9, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_5, FEATURE_6, FEATURE_8, FEATURE_12, });
		TERMINAL_26.addFollower(TERMINAL_10, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, FEATURE_8, FEATURE_12, });
		TERMINAL_26.addFollower(TERMINAL_11, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_12, });
		TERMINAL_35.addFollower(TERMINAL_3, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, FEATURE_1, FEATURE_13, });
		TERMINAL_35.addFollower(TERMINAL_4, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_3, FEATURE_4, FEATURE_0, FEATURE_1, FEATURE_13, });
		TERMINAL_35.addFollower(TERMINAL_5, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_3, FEATURE_4, FEATURE_0, FEATURE_1, FEATURE_13, });
		TERMINAL_35.addFollower(TERMINAL_6, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_4, FEATURE_0, FEATURE_1, FEATURE_13, });
		TERMINAL_35.addFollower(TERMINAL_7, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_4, FEATURE_0, FEATURE_1, FEATURE_13, });
		TERMINAL_35.addFollower(TERMINAL_8, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_1, FEATURE_13, });
		TERMINAL_35.addFollower(TERMINAL_9, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_5, FEATURE_6, FEATURE_1, FEATURE_13, });
		TERMINAL_35.addFollower(TERMINAL_10, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, FEATURE_1, FEATURE_13, });
		TERMINAL_35.addFollower(TERMINAL_11, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_7, FEATURE_1, FEATURE_13, });
		TERMINAL_35.addFollower(TERMINAL_12, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_13, });
		TERMINAL_14.addFollower(TERMINAL_13, EMPTY_FEATURE_ARRAY);
		TERMINAL_14.addFollower(TERMINAL_14, EMPTY_FEATURE_ARRAY);
		TERMINAL_14.addFollower(TERMINAL_16, EMPTY_FEATURE_ARRAY);
		TERMINAL_14.addFollower(TERMINAL_22, EMPTY_FEATURE_ARRAY);
		TERMINAL_14.addFollower(TERMINAL_23, EMPTY_FEATURE_ARRAY);
		TERMINAL_14.addFollower(TERMINAL_24, EMPTY_FEATURE_ARRAY);
		TERMINAL_14.addFollower(TERMINAL_25, EMPTY_FEATURE_ARRAY);
		TERMINAL_14.addFollower(TERMINAL_26, EMPTY_FEATURE_ARRAY);
		TERMINAL_14.addFollower(TERMINAL_28, EMPTY_FEATURE_ARRAY);
		TERMINAL_14.addFollower(TERMINAL_29, EMPTY_FEATURE_ARRAY);
		TERMINAL_14.addFollower(TERMINAL_30, EMPTY_FEATURE_ARRAY);
		TERMINAL_14.addFollower(TERMINAL_31, EMPTY_FEATURE_ARRAY);
		TERMINAL_14.addFollower(TERMINAL_32, EMPTY_FEATURE_ARRAY);
		TERMINAL_14.addFollower(TERMINAL_33, EMPTY_FEATURE_ARRAY);
		TERMINAL_6.addFollower(TERMINAL_21, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_14, });
		TERMINAL_6.addFollower(TERMINAL_3, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, FEATURE_9, FEATURE_14, });
		TERMINAL_6.addFollower(TERMINAL_4, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_3, FEATURE_4, FEATURE_0, FEATURE_9, FEATURE_14, });
		TERMINAL_6.addFollower(TERMINAL_5, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_3, FEATURE_4, FEATURE_0, FEATURE_9, FEATURE_14, });
		TERMINAL_6.addFollower(TERMINAL_6, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_4, FEATURE_0, FEATURE_9, FEATURE_14, });
		TERMINAL_6.addFollower(TERMINAL_7, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_4, FEATURE_0, FEATURE_9, FEATURE_14, });
		TERMINAL_6.addFollower(TERMINAL_8, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_9, FEATURE_14, });
		TERMINAL_6.addFollower(TERMINAL_9, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_5, FEATURE_6, FEATURE_8, FEATURE_7, FEATURE_9, FEATURE_14, });
		TERMINAL_6.addFollower(TERMINAL_10, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, FEATURE_8, FEATURE_7, FEATURE_9, FEATURE_14, });
		TERMINAL_6.addFollower(TERMINAL_11, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_7, FEATURE_9, FEATURE_14, });
		TERMINAL_7.addFollower(TERMINAL_21, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_14, });
		TERMINAL_7.addFollower(TERMINAL_3, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, FEATURE_9, FEATURE_14, });
		TERMINAL_7.addFollower(TERMINAL_4, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_3, FEATURE_4, FEATURE_0, FEATURE_9, FEATURE_14, });
		TERMINAL_7.addFollower(TERMINAL_5, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_3, FEATURE_4, FEATURE_0, FEATURE_9, FEATURE_14, });
		TERMINAL_7.addFollower(TERMINAL_6, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_4, FEATURE_0, FEATURE_9, FEATURE_14, });
		TERMINAL_7.addFollower(TERMINAL_7, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_4, FEATURE_0, FEATURE_9, FEATURE_14, });
		TERMINAL_7.addFollower(TERMINAL_8, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_9, FEATURE_14, });
		TERMINAL_7.addFollower(TERMINAL_9, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_5, FEATURE_6, FEATURE_8, FEATURE_7, FEATURE_9, FEATURE_14, });
		TERMINAL_7.addFollower(TERMINAL_10, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, FEATURE_8, FEATURE_7, FEATURE_9, FEATURE_14, });
		TERMINAL_7.addFollower(TERMINAL_11, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_7, FEATURE_9, FEATURE_14, });
		TERMINAL_28.addFollower(TERMINAL_4, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_3, FEATURE_5, FEATURE_6, FEATURE_8, FEATURE_15, });
		TERMINAL_28.addFollower(TERMINAL_5, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_3, FEATURE_5, FEATURE_6, FEATURE_8, FEATURE_15, });
		TERMINAL_28.addFollower(TERMINAL_9, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_5, FEATURE_6, FEATURE_8, FEATURE_15, });
		TERMINAL_28.addFollower(TERMINAL_10, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, FEATURE_8, FEATURE_15, });
		TERMINAL_28.addFollower(TERMINAL_11, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_15, });
		TERMINAL_29.addFollower(TERMINAL_4, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_3, FEATURE_5, FEATURE_6, FEATURE_8, FEATURE_15, });
		TERMINAL_29.addFollower(TERMINAL_5, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_3, FEATURE_5, FEATURE_6, FEATURE_8, FEATURE_15, });
		TERMINAL_29.addFollower(TERMINAL_9, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_5, FEATURE_6, FEATURE_8, FEATURE_15, });
		TERMINAL_29.addFollower(TERMINAL_10, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, FEATURE_8, FEATURE_15, });
		TERMINAL_29.addFollower(TERMINAL_11, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_15, });
		TERMINAL_30.addFollower(TERMINAL_4, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_3, FEATURE_5, FEATURE_6, FEATURE_8, FEATURE_15, });
		TERMINAL_30.addFollower(TERMINAL_5, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_3, FEATURE_5, FEATURE_6, FEATURE_8, FEATURE_15, });
		TERMINAL_30.addFollower(TERMINAL_9, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_5, FEATURE_6, FEATURE_8, FEATURE_15, });
		TERMINAL_30.addFollower(TERMINAL_10, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, FEATURE_8, FEATURE_15, });
		TERMINAL_30.addFollower(TERMINAL_11, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_15, });
		TERMINAL_31.addFollower(TERMINAL_4, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_3, FEATURE_5, FEATURE_6, FEATURE_8, FEATURE_15, });
		TERMINAL_31.addFollower(TERMINAL_5, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_3, FEATURE_5, FEATURE_6, FEATURE_8, FEATURE_15, });
		TERMINAL_31.addFollower(TERMINAL_9, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_5, FEATURE_6, FEATURE_8, FEATURE_15, });
		TERMINAL_31.addFollower(TERMINAL_10, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, FEATURE_8, FEATURE_15, });
		TERMINAL_31.addFollower(TERMINAL_11, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_15, });
		TERMINAL_32.addFollower(TERMINAL_4, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_3, FEATURE_5, FEATURE_6, FEATURE_8, FEATURE_15, });
		TERMINAL_32.addFollower(TERMINAL_5, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_3, FEATURE_5, FEATURE_6, FEATURE_8, FEATURE_15, });
		TERMINAL_32.addFollower(TERMINAL_9, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_5, FEATURE_6, FEATURE_8, FEATURE_15, });
		TERMINAL_32.addFollower(TERMINAL_10, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, FEATURE_8, FEATURE_15, });
		TERMINAL_32.addFollower(TERMINAL_11, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_15, });
		TERMINAL_33.addFollower(TERMINAL_4, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_3, FEATURE_5, FEATURE_6, FEATURE_8, FEATURE_15, });
		TERMINAL_33.addFollower(TERMINAL_5, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_3, FEATURE_5, FEATURE_6, FEATURE_8, FEATURE_15, });
		TERMINAL_33.addFollower(TERMINAL_9, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_5, FEATURE_6, FEATURE_8, FEATURE_15, });
		TERMINAL_33.addFollower(TERMINAL_10, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, FEATURE_8, FEATURE_15, });
		TERMINAL_33.addFollower(TERMINAL_11, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_15, });
		TERMINAL_4.addFollower(TERMINAL_13, EMPTY_FEATURE_ARRAY);
		TERMINAL_4.addFollower(TERMINAL_14, EMPTY_FEATURE_ARRAY);
		TERMINAL_4.addFollower(TERMINAL_16, EMPTY_FEATURE_ARRAY);
		TERMINAL_4.addFollower(TERMINAL_22, EMPTY_FEATURE_ARRAY);
		TERMINAL_4.addFollower(TERMINAL_23, EMPTY_FEATURE_ARRAY);
		TERMINAL_4.addFollower(TERMINAL_24, EMPTY_FEATURE_ARRAY);
		TERMINAL_4.addFollower(TERMINAL_25, EMPTY_FEATURE_ARRAY);
		TERMINAL_4.addFollower(TERMINAL_26, EMPTY_FEATURE_ARRAY);
		TERMINAL_4.addFollower(TERMINAL_28, EMPTY_FEATURE_ARRAY);
		TERMINAL_4.addFollower(TERMINAL_29, EMPTY_FEATURE_ARRAY);
		TERMINAL_4.addFollower(TERMINAL_30, EMPTY_FEATURE_ARRAY);
		TERMINAL_4.addFollower(TERMINAL_31, EMPTY_FEATURE_ARRAY);
		TERMINAL_4.addFollower(TERMINAL_32, EMPTY_FEATURE_ARRAY);
		TERMINAL_4.addFollower(TERMINAL_33, EMPTY_FEATURE_ARRAY);
		TERMINAL_5.addFollower(TERMINAL_13, EMPTY_FEATURE_ARRAY);
		TERMINAL_5.addFollower(TERMINAL_14, EMPTY_FEATURE_ARRAY);
		TERMINAL_5.addFollower(TERMINAL_23, EMPTY_FEATURE_ARRAY);
		TERMINAL_5.addFollower(TERMINAL_24, EMPTY_FEATURE_ARRAY);
		TERMINAL_5.addFollower(TERMINAL_25, EMPTY_FEATURE_ARRAY);
		TERMINAL_5.addFollower(TERMINAL_26, EMPTY_FEATURE_ARRAY);
		TERMINAL_5.addFollower(TERMINAL_28, EMPTY_FEATURE_ARRAY);
		TERMINAL_5.addFollower(TERMINAL_29, EMPTY_FEATURE_ARRAY);
		TERMINAL_5.addFollower(TERMINAL_30, EMPTY_FEATURE_ARRAY);
		TERMINAL_5.addFollower(TERMINAL_31, EMPTY_FEATURE_ARRAY);
		TERMINAL_5.addFollower(TERMINAL_32, EMPTY_FEATURE_ARRAY);
		TERMINAL_5.addFollower(TERMINAL_33, EMPTY_FEATURE_ARRAY);
		TERMINAL_9.addFollower(TERMINAL_13, EMPTY_FEATURE_ARRAY);
		TERMINAL_9.addFollower(TERMINAL_14, EMPTY_FEATURE_ARRAY);
		TERMINAL_9.addFollower(TERMINAL_23, EMPTY_FEATURE_ARRAY);
		TERMINAL_9.addFollower(TERMINAL_24, EMPTY_FEATURE_ARRAY);
		TERMINAL_9.addFollower(TERMINAL_25, EMPTY_FEATURE_ARRAY);
		TERMINAL_9.addFollower(TERMINAL_26, EMPTY_FEATURE_ARRAY);
		TERMINAL_9.addFollower(TERMINAL_28, EMPTY_FEATURE_ARRAY);
		TERMINAL_9.addFollower(TERMINAL_29, EMPTY_FEATURE_ARRAY);
		TERMINAL_9.addFollower(TERMINAL_30, EMPTY_FEATURE_ARRAY);
		TERMINAL_9.addFollower(TERMINAL_31, EMPTY_FEATURE_ARRAY);
		TERMINAL_9.addFollower(TERMINAL_32, EMPTY_FEATURE_ARRAY);
		TERMINAL_9.addFollower(TERMINAL_33, EMPTY_FEATURE_ARRAY);
	}
	// wire the terminals
	static {
		wire0();
	}
}
