/**
 * <copyright>
 * </copyright>
 *
 * 
 */
package hydraconstraints.resource.hydraConst.grammar;

public class HydraConstGrammarInformationProvider {
	
	public final static org.eclipse.emf.ecore.EStructuralFeature ANONYMOUS_FEATURE = org.eclipse.emf.ecore.EcoreFactory.eINSTANCE.createEAttribute();
	static {
		ANONYMOUS_FEATURE.setName("_");
	}
	
	public final static HydraConstGrammarInformationProvider INSTANCE = new HydraConstGrammarInformationProvider();
	
	private java.util.Set<String> keywords;
	
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstKeyword HYDRACONST_0_0_0_0 = new hydraconstraints.resource.hydraConst.grammar.HydraConstKeyword("import", hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstPlaceholder HYDRACONST_0_0_0_1 = new hydraconstraints.resource.hydraConst.grammar.HydraConstPlaceholder(hydraconstraints.HydraconstraintsPackage.eINSTANCE.getModel().getEStructuralFeature(hydraconstraints.HydraconstraintsPackage.MODEL__FEATURE_LIST), "TEXT", hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE, 0);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstKeyword HYDRACONST_0_0_0_2 = new hydraconstraints.resource.hydraConst.grammar.HydraConstKeyword(";", hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstContainment HYDRACONST_0_0_0_3_0_0_0 = new hydraconstraints.resource.hydraConst.grammar.HydraConstContainment(hydraconstraints.HydraconstraintsPackage.eINSTANCE.getModel().getEStructuralFeature(hydraconstraints.HydraconstraintsPackage.MODEL__CONSTRAINTS), hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE, 0);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstKeyword HYDRACONST_0_0_0_3_0_0_1 = new hydraconstraints.resource.hydraConst.grammar.HydraConstKeyword(";", hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstSequence HYDRACONST_0_0_0_3_0_0 = new hydraconstraints.resource.hydraConst.grammar.HydraConstSequence(hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE, HYDRACONST_0_0_0_3_0_0_0, HYDRACONST_0_0_0_3_0_0_1);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstChoice HYDRACONST_0_0_0_3_0 = new hydraconstraints.resource.hydraConst.grammar.HydraConstChoice(hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE, HYDRACONST_0_0_0_3_0_0);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstCompound HYDRACONST_0_0_0_3 = new hydraconstraints.resource.hydraConst.grammar.HydraConstCompound(HYDRACONST_0_0_0_3_0, hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.STAR);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstSequence HYDRACONST_0_0_0 = new hydraconstraints.resource.hydraConst.grammar.HydraConstSequence(hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE, HYDRACONST_0_0_0_0, HYDRACONST_0_0_0_1, HYDRACONST_0_0_0_2, HYDRACONST_0_0_0_3);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstChoice HYDRACONST_0_0 = new hydraconstraints.resource.hydraConst.grammar.HydraConstChoice(hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE, HYDRACONST_0_0_0);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstRule HYDRACONST_0 = new hydraconstraints.resource.hydraConst.grammar.HydraConstRule(hydraconstraints.HydraconstraintsPackage.eINSTANCE.getModel(), HYDRACONST_0_0, hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstContainment HYDRACONST_1_0_0_0 = new hydraconstraints.resource.hydraConst.grammar.HydraConstContainment(hydraconstraints.HydraconstraintsPackage.eINSTANCE.getConstraint().getEStructuralFeature(hydraconstraints.HydraconstraintsPackage.CONSTRAINT__OPERATORS), hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE, 0);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstSequence HYDRACONST_1_0_0 = new hydraconstraints.resource.hydraConst.grammar.HydraConstSequence(hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE, HYDRACONST_1_0_0_0);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstKeyword HYDRACONST_1_0_1_0 = new hydraconstraints.resource.hydraConst.grammar.HydraConstKeyword("(", hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstContainment HYDRACONST_1_0_1_1 = new hydraconstraints.resource.hydraConst.grammar.HydraConstContainment(hydraconstraints.HydraconstraintsPackage.eINSTANCE.getConstraint().getEStructuralFeature(hydraconstraints.HydraconstraintsPackage.CONSTRAINT__OPERATORS), hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE, 0);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstKeyword HYDRACONST_1_0_1_2 = new hydraconstraints.resource.hydraConst.grammar.HydraConstKeyword(")", hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstSequence HYDRACONST_1_0_1 = new hydraconstraints.resource.hydraConst.grammar.HydraConstSequence(hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE, HYDRACONST_1_0_1_0, HYDRACONST_1_0_1_1, HYDRACONST_1_0_1_2);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstChoice HYDRACONST_1_0 = new hydraconstraints.resource.hydraConst.grammar.HydraConstChoice(hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE, HYDRACONST_1_0_0, HYDRACONST_1_0_1);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstRule HYDRACONST_1 = new hydraconstraints.resource.hydraConst.grammar.HydraConstRule(hydraconstraints.HydraconstraintsPackage.eINSTANCE.getConstraint(), HYDRACONST_1_0, hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstKeyword HYDRACONST_2_0_0_0 = new hydraconstraints.resource.hydraConst.grammar.HydraConstKeyword("(", hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstContainment HYDRACONST_2_0_0_1 = new hydraconstraints.resource.hydraConst.grammar.HydraConstContainment(hydraconstraints.HydraconstraintsPackage.eINSTANCE.getBoolPriorityOperand1().getEStructuralFeature(hydraconstraints.HydraconstraintsPackage.BOOL_PRIORITY_OPERAND1__BOOL_PRIORITY_OP1), hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE, 0);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstKeyword HYDRACONST_2_0_0_2 = new hydraconstraints.resource.hydraConst.grammar.HydraConstKeyword(")", hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstSequence HYDRACONST_2_0_0 = new hydraconstraints.resource.hydraConst.grammar.HydraConstSequence(hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE, HYDRACONST_2_0_0_0, HYDRACONST_2_0_0_1, HYDRACONST_2_0_0_2);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstContainment HYDRACONST_2_0_1_0 = new hydraconstraints.resource.hydraConst.grammar.HydraConstContainment(hydraconstraints.HydraconstraintsPackage.eINSTANCE.getBoolPriorityOperand1().getEStructuralFeature(hydraconstraints.HydraconstraintsPackage.BOOL_PRIORITY_OPERAND1__BOOL_PRIORITY_OP1), hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE, 0);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstSequence HYDRACONST_2_0_1 = new hydraconstraints.resource.hydraConst.grammar.HydraConstSequence(hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE, HYDRACONST_2_0_1_0);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstChoice HYDRACONST_2_0 = new hydraconstraints.resource.hydraConst.grammar.HydraConstChoice(hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE, HYDRACONST_2_0_0, HYDRACONST_2_0_1);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstRule HYDRACONST_2 = new hydraconstraints.resource.hydraConst.grammar.HydraConstRule(hydraconstraints.HydraconstraintsPackage.eINSTANCE.getBoolPriorityOperand1(), HYDRACONST_2_0, hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstKeyword HYDRACONST_3_0_0_0 = new hydraconstraints.resource.hydraConst.grammar.HydraConstKeyword("(", hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstContainment HYDRACONST_3_0_0_1 = new hydraconstraints.resource.hydraConst.grammar.HydraConstContainment(hydraconstraints.HydraconstraintsPackage.eINSTANCE.getBoolPriorityOperand2().getEStructuralFeature(hydraconstraints.HydraconstraintsPackage.BOOL_PRIORITY_OPERAND2__BOOL_PRIORITY_OP2), hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE, 0);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstKeyword HYDRACONST_3_0_0_2 = new hydraconstraints.resource.hydraConst.grammar.HydraConstKeyword(")", hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstSequence HYDRACONST_3_0_0 = new hydraconstraints.resource.hydraConst.grammar.HydraConstSequence(hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE, HYDRACONST_3_0_0_0, HYDRACONST_3_0_0_1, HYDRACONST_3_0_0_2);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstContainment HYDRACONST_3_0_1_0 = new hydraconstraints.resource.hydraConst.grammar.HydraConstContainment(hydraconstraints.HydraconstraintsPackage.eINSTANCE.getBoolPriorityOperand2().getEStructuralFeature(hydraconstraints.HydraconstraintsPackage.BOOL_PRIORITY_OPERAND2__BOOL_PRIORITY_OP2), hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE, 0);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstSequence HYDRACONST_3_0_1 = new hydraconstraints.resource.hydraConst.grammar.HydraConstSequence(hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE, HYDRACONST_3_0_1_0);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstChoice HYDRACONST_3_0 = new hydraconstraints.resource.hydraConst.grammar.HydraConstChoice(hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE, HYDRACONST_3_0_0, HYDRACONST_3_0_1);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstRule HYDRACONST_3 = new hydraconstraints.resource.hydraConst.grammar.HydraConstRule(hydraconstraints.HydraconstraintsPackage.eINSTANCE.getBoolPriorityOperand2(), HYDRACONST_3_0, hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstContainment HYDRACONST_4_0_0_0 = new hydraconstraints.resource.hydraConst.grammar.HydraConstContainment(hydraconstraints.HydraconstraintsPackage.eINSTANCE.getNumPriorityOperand1().getEStructuralFeature(hydraconstraints.HydraconstraintsPackage.NUM_PRIORITY_OPERAND1__NUM_PRIORITY_OP1), hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE, 0);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstSequence HYDRACONST_4_0_0 = new hydraconstraints.resource.hydraConst.grammar.HydraConstSequence(hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE, HYDRACONST_4_0_0_0);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstKeyword HYDRACONST_4_0_1_0 = new hydraconstraints.resource.hydraConst.grammar.HydraConstKeyword("(", hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstContainment HYDRACONST_4_0_1_1 = new hydraconstraints.resource.hydraConst.grammar.HydraConstContainment(hydraconstraints.HydraconstraintsPackage.eINSTANCE.getNumPriorityOperand1().getEStructuralFeature(hydraconstraints.HydraconstraintsPackage.NUM_PRIORITY_OPERAND1__NUM_PRIORITY_OP1), hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE, 0);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstKeyword HYDRACONST_4_0_1_2 = new hydraconstraints.resource.hydraConst.grammar.HydraConstKeyword(")", hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstSequence HYDRACONST_4_0_1 = new hydraconstraints.resource.hydraConst.grammar.HydraConstSequence(hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE, HYDRACONST_4_0_1_0, HYDRACONST_4_0_1_1, HYDRACONST_4_0_1_2);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstChoice HYDRACONST_4_0 = new hydraconstraints.resource.hydraConst.grammar.HydraConstChoice(hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE, HYDRACONST_4_0_0, HYDRACONST_4_0_1);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstRule HYDRACONST_4 = new hydraconstraints.resource.hydraConst.grammar.HydraConstRule(hydraconstraints.HydraconstraintsPackage.eINSTANCE.getNumPriorityOperand1(), HYDRACONST_4_0, hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstContainment HYDRACONST_5_0_0_0 = new hydraconstraints.resource.hydraConst.grammar.HydraConstContainment(hydraconstraints.HydraconstraintsPackage.eINSTANCE.getNumPriorityOperand2().getEStructuralFeature(hydraconstraints.HydraconstraintsPackage.NUM_PRIORITY_OPERAND2__NUM_PRIORITY_OP2), hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE, 0);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstSequence HYDRACONST_5_0_0 = new hydraconstraints.resource.hydraConst.grammar.HydraConstSequence(hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE, HYDRACONST_5_0_0_0);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstKeyword HYDRACONST_5_0_1_0 = new hydraconstraints.resource.hydraConst.grammar.HydraConstKeyword("(", hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstContainment HYDRACONST_5_0_1_1 = new hydraconstraints.resource.hydraConst.grammar.HydraConstContainment(hydraconstraints.HydraconstraintsPackage.eINSTANCE.getNumPriorityOperand2().getEStructuralFeature(hydraconstraints.HydraconstraintsPackage.NUM_PRIORITY_OPERAND2__NUM_PRIORITY_OP2), hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE, 0);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstKeyword HYDRACONST_5_0_1_2 = new hydraconstraints.resource.hydraConst.grammar.HydraConstKeyword(")", hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstSequence HYDRACONST_5_0_1 = new hydraconstraints.resource.hydraConst.grammar.HydraConstSequence(hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE, HYDRACONST_5_0_1_0, HYDRACONST_5_0_1_1, HYDRACONST_5_0_1_2);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstChoice HYDRACONST_5_0 = new hydraconstraints.resource.hydraConst.grammar.HydraConstChoice(hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE, HYDRACONST_5_0_0, HYDRACONST_5_0_1);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstRule HYDRACONST_5 = new hydraconstraints.resource.hydraConst.grammar.HydraConstRule(hydraconstraints.HydraconstraintsPackage.eINSTANCE.getNumPriorityOperand2(), HYDRACONST_5_0, hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstContainment HYDRACONST_6_0_0_0 = new hydraconstraints.resource.hydraConst.grammar.HydraConstContainment(hydraconstraints.HydraconstraintsPackage.eINSTANCE.getAnd().getEStructuralFeature(hydraconstraints.HydraconstraintsPackage.AND__BINARY_OP1), hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE, 0);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstKeyword HYDRACONST_6_0_0_1 = new hydraconstraints.resource.hydraConst.grammar.HydraConstKeyword("and", hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstContainment HYDRACONST_6_0_0_2 = new hydraconstraints.resource.hydraConst.grammar.HydraConstContainment(hydraconstraints.HydraconstraintsPackage.eINSTANCE.getAnd().getEStructuralFeature(hydraconstraints.HydraconstraintsPackage.AND__BINARY_OP2), hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE, 0);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstSequence HYDRACONST_6_0_0 = new hydraconstraints.resource.hydraConst.grammar.HydraConstSequence(hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE, HYDRACONST_6_0_0_0, HYDRACONST_6_0_0_1, HYDRACONST_6_0_0_2);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstChoice HYDRACONST_6_0 = new hydraconstraints.resource.hydraConst.grammar.HydraConstChoice(hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE, HYDRACONST_6_0_0);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstRule HYDRACONST_6 = new hydraconstraints.resource.hydraConst.grammar.HydraConstRule(hydraconstraints.HydraconstraintsPackage.eINSTANCE.getAnd(), HYDRACONST_6_0, hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstContainment HYDRACONST_7_0_0_0 = new hydraconstraints.resource.hydraConst.grammar.HydraConstContainment(hydraconstraints.HydraconstraintsPackage.eINSTANCE.getOr().getEStructuralFeature(hydraconstraints.HydraconstraintsPackage.OR__BINARY_OP1), hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE, 0);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstKeyword HYDRACONST_7_0_0_1 = new hydraconstraints.resource.hydraConst.grammar.HydraConstKeyword("or", hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstContainment HYDRACONST_7_0_0_2 = new hydraconstraints.resource.hydraConst.grammar.HydraConstContainment(hydraconstraints.HydraconstraintsPackage.eINSTANCE.getOr().getEStructuralFeature(hydraconstraints.HydraconstraintsPackage.OR__BINARY_OP2), hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE, 0);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstSequence HYDRACONST_7_0_0 = new hydraconstraints.resource.hydraConst.grammar.HydraConstSequence(hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE, HYDRACONST_7_0_0_0, HYDRACONST_7_0_0_1, HYDRACONST_7_0_0_2);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstChoice HYDRACONST_7_0 = new hydraconstraints.resource.hydraConst.grammar.HydraConstChoice(hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE, HYDRACONST_7_0_0);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstRule HYDRACONST_7 = new hydraconstraints.resource.hydraConst.grammar.HydraConstRule(hydraconstraints.HydraconstraintsPackage.eINSTANCE.getOr(), HYDRACONST_7_0, hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstContainment HYDRACONST_8_0_0_0 = new hydraconstraints.resource.hydraConst.grammar.HydraConstContainment(hydraconstraints.HydraconstraintsPackage.eINSTANCE.getXor().getEStructuralFeature(hydraconstraints.HydraconstraintsPackage.XOR__BINARY_OP1), hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE, 0);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstKeyword HYDRACONST_8_0_0_1 = new hydraconstraints.resource.hydraConst.grammar.HydraConstKeyword("xor", hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstContainment HYDRACONST_8_0_0_2 = new hydraconstraints.resource.hydraConst.grammar.HydraConstContainment(hydraconstraints.HydraconstraintsPackage.eINSTANCE.getXor().getEStructuralFeature(hydraconstraints.HydraconstraintsPackage.XOR__BINARY_OP2), hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE, 0);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstSequence HYDRACONST_8_0_0 = new hydraconstraints.resource.hydraConst.grammar.HydraConstSequence(hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE, HYDRACONST_8_0_0_0, HYDRACONST_8_0_0_1, HYDRACONST_8_0_0_2);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstChoice HYDRACONST_8_0 = new hydraconstraints.resource.hydraConst.grammar.HydraConstChoice(hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE, HYDRACONST_8_0_0);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstRule HYDRACONST_8 = new hydraconstraints.resource.hydraConst.grammar.HydraConstRule(hydraconstraints.HydraconstraintsPackage.eINSTANCE.getXor(), HYDRACONST_8_0, hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstContainment HYDRACONST_9_0_0_0 = new hydraconstraints.resource.hydraConst.grammar.HydraConstContainment(hydraconstraints.HydraconstraintsPackage.eINSTANCE.getImplies().getEStructuralFeature(hydraconstraints.HydraconstraintsPackage.IMPLIES__BINARY_OP1), hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE, 0);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstKeyword HYDRACONST_9_0_0_1 = new hydraconstraints.resource.hydraConst.grammar.HydraConstKeyword("implies", hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstContainment HYDRACONST_9_0_0_2 = new hydraconstraints.resource.hydraConst.grammar.HydraConstContainment(hydraconstraints.HydraconstraintsPackage.eINSTANCE.getImplies().getEStructuralFeature(hydraconstraints.HydraconstraintsPackage.IMPLIES__BINARY_OP2), hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE, 0);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstSequence HYDRACONST_9_0_0 = new hydraconstraints.resource.hydraConst.grammar.HydraConstSequence(hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE, HYDRACONST_9_0_0_0, HYDRACONST_9_0_0_1, HYDRACONST_9_0_0_2);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstChoice HYDRACONST_9_0 = new hydraconstraints.resource.hydraConst.grammar.HydraConstChoice(hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE, HYDRACONST_9_0_0);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstRule HYDRACONST_9 = new hydraconstraints.resource.hydraConst.grammar.HydraConstRule(hydraconstraints.HydraconstraintsPackage.eINSTANCE.getImplies(), HYDRACONST_9_0, hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstKeyword HYDRACONST_10_0_0_0 = new hydraconstraints.resource.hydraConst.grammar.HydraConstKeyword("!", hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstContainment HYDRACONST_10_0_0_1 = new hydraconstraints.resource.hydraConst.grammar.HydraConstContainment(hydraconstraints.HydraconstraintsPackage.eINSTANCE.getNeg().getEStructuralFeature(hydraconstraints.HydraconstraintsPackage.NEG__UNARY_OP), hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE, 0);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstSequence HYDRACONST_10_0_0 = new hydraconstraints.resource.hydraConst.grammar.HydraConstSequence(hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE, HYDRACONST_10_0_0_0, HYDRACONST_10_0_0_1);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstChoice HYDRACONST_10_0 = new hydraconstraints.resource.hydraConst.grammar.HydraConstChoice(hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE, HYDRACONST_10_0_0);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstRule HYDRACONST_10 = new hydraconstraints.resource.hydraConst.grammar.HydraConstRule(hydraconstraints.HydraconstraintsPackage.eINSTANCE.getNeg(), HYDRACONST_10_0, hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstContainment HYDRACONST_11_0_0_0 = new hydraconstraints.resource.hydraConst.grammar.HydraConstContainment(hydraconstraints.HydraconstraintsPackage.eINSTANCE.getPlus().getEStructuralFeature(hydraconstraints.HydraconstraintsPackage.PLUS__NUM_OP1), hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE, 0);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstKeyword HYDRACONST_11_0_0_1 = new hydraconstraints.resource.hydraConst.grammar.HydraConstKeyword("+", hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstContainment HYDRACONST_11_0_0_2 = new hydraconstraints.resource.hydraConst.grammar.HydraConstContainment(hydraconstraints.HydraconstraintsPackage.eINSTANCE.getPlus().getEStructuralFeature(hydraconstraints.HydraconstraintsPackage.PLUS__NUM_OP2), hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE, 0);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstSequence HYDRACONST_11_0_0 = new hydraconstraints.resource.hydraConst.grammar.HydraConstSequence(hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE, HYDRACONST_11_0_0_0, HYDRACONST_11_0_0_1, HYDRACONST_11_0_0_2);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstChoice HYDRACONST_11_0 = new hydraconstraints.resource.hydraConst.grammar.HydraConstChoice(hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE, HYDRACONST_11_0_0);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstRule HYDRACONST_11 = new hydraconstraints.resource.hydraConst.grammar.HydraConstRule(hydraconstraints.HydraconstraintsPackage.eINSTANCE.getPlus(), HYDRACONST_11_0, hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstContainment HYDRACONST_12_0_0_0 = new hydraconstraints.resource.hydraConst.grammar.HydraConstContainment(hydraconstraints.HydraconstraintsPackage.eINSTANCE.getMinus().getEStructuralFeature(hydraconstraints.HydraconstraintsPackage.MINUS__NUM_OP1), hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE, 0);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstKeyword HYDRACONST_12_0_0_1 = new hydraconstraints.resource.hydraConst.grammar.HydraConstKeyword("-", hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstContainment HYDRACONST_12_0_0_2 = new hydraconstraints.resource.hydraConst.grammar.HydraConstContainment(hydraconstraints.HydraconstraintsPackage.eINSTANCE.getMinus().getEStructuralFeature(hydraconstraints.HydraconstraintsPackage.MINUS__NUM_OP2), hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE, 0);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstSequence HYDRACONST_12_0_0 = new hydraconstraints.resource.hydraConst.grammar.HydraConstSequence(hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE, HYDRACONST_12_0_0_0, HYDRACONST_12_0_0_1, HYDRACONST_12_0_0_2);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstChoice HYDRACONST_12_0 = new hydraconstraints.resource.hydraConst.grammar.HydraConstChoice(hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE, HYDRACONST_12_0_0);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstRule HYDRACONST_12 = new hydraconstraints.resource.hydraConst.grammar.HydraConstRule(hydraconstraints.HydraconstraintsPackage.eINSTANCE.getMinus(), HYDRACONST_12_0, hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstContainment HYDRACONST_13_0_0_0 = new hydraconstraints.resource.hydraConst.grammar.HydraConstContainment(hydraconstraints.HydraconstraintsPackage.eINSTANCE.getMul().getEStructuralFeature(hydraconstraints.HydraconstraintsPackage.MUL__NUM_OP1), hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE, 0);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstKeyword HYDRACONST_13_0_0_1 = new hydraconstraints.resource.hydraConst.grammar.HydraConstKeyword("*", hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstContainment HYDRACONST_13_0_0_2 = new hydraconstraints.resource.hydraConst.grammar.HydraConstContainment(hydraconstraints.HydraconstraintsPackage.eINSTANCE.getMul().getEStructuralFeature(hydraconstraints.HydraconstraintsPackage.MUL__NUM_OP2), hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE, 0);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstSequence HYDRACONST_13_0_0 = new hydraconstraints.resource.hydraConst.grammar.HydraConstSequence(hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE, HYDRACONST_13_0_0_0, HYDRACONST_13_0_0_1, HYDRACONST_13_0_0_2);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstChoice HYDRACONST_13_0 = new hydraconstraints.resource.hydraConst.grammar.HydraConstChoice(hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE, HYDRACONST_13_0_0);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstRule HYDRACONST_13 = new hydraconstraints.resource.hydraConst.grammar.HydraConstRule(hydraconstraints.HydraconstraintsPackage.eINSTANCE.getMul(), HYDRACONST_13_0, hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstContainment HYDRACONST_14_0_0_0 = new hydraconstraints.resource.hydraConst.grammar.HydraConstContainment(hydraconstraints.HydraconstraintsPackage.eINSTANCE.getDiv().getEStructuralFeature(hydraconstraints.HydraconstraintsPackage.DIV__NUM_OP1), hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE, 0);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstKeyword HYDRACONST_14_0_0_1 = new hydraconstraints.resource.hydraConst.grammar.HydraConstKeyword("/", hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstContainment HYDRACONST_14_0_0_2 = new hydraconstraints.resource.hydraConst.grammar.HydraConstContainment(hydraconstraints.HydraconstraintsPackage.eINSTANCE.getDiv().getEStructuralFeature(hydraconstraints.HydraconstraintsPackage.DIV__NUM_OP2), hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE, 0);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstSequence HYDRACONST_14_0_0 = new hydraconstraints.resource.hydraConst.grammar.HydraConstSequence(hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE, HYDRACONST_14_0_0_0, HYDRACONST_14_0_0_1, HYDRACONST_14_0_0_2);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstChoice HYDRACONST_14_0 = new hydraconstraints.resource.hydraConst.grammar.HydraConstChoice(hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE, HYDRACONST_14_0_0);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstRule HYDRACONST_14 = new hydraconstraints.resource.hydraConst.grammar.HydraConstRule(hydraconstraints.HydraconstraintsPackage.eINSTANCE.getDiv(), HYDRACONST_14_0, hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstContainment HYDRACONST_15_0_0_0 = new hydraconstraints.resource.hydraConst.grammar.HydraConstContainment(hydraconstraints.HydraconstraintsPackage.eINSTANCE.getContext().getEStructuralFeature(hydraconstraints.HydraconstraintsPackage.CONTEXT__CONTEXT_OP1), hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE, 0);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstKeyword HYDRACONST_15_0_0_1 = new hydraconstraints.resource.hydraConst.grammar.HydraConstKeyword("[", hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstContainment HYDRACONST_15_0_0_2 = new hydraconstraints.resource.hydraConst.grammar.HydraConstContainment(hydraconstraints.HydraconstraintsPackage.eINSTANCE.getContext().getEStructuralFeature(hydraconstraints.HydraconstraintsPackage.CONTEXT__CONTEXT_OP2), hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE, 0);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstKeyword HYDRACONST_15_0_0_3 = new hydraconstraints.resource.hydraConst.grammar.HydraConstKeyword("]", hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstSequence HYDRACONST_15_0_0 = new hydraconstraints.resource.hydraConst.grammar.HydraConstSequence(hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE, HYDRACONST_15_0_0_0, HYDRACONST_15_0_0_1, HYDRACONST_15_0_0_2, HYDRACONST_15_0_0_3);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstChoice HYDRACONST_15_0 = new hydraconstraints.resource.hydraConst.grammar.HydraConstChoice(hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE, HYDRACONST_15_0_0);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstRule HYDRACONST_15 = new hydraconstraints.resource.hydraConst.grammar.HydraConstRule(hydraconstraints.HydraconstraintsPackage.eINSTANCE.getContext(), HYDRACONST_15_0, hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstKeyword HYDRACONST_16_0_0_0 = new hydraconstraints.resource.hydraConst.grammar.HydraConstKeyword("all", hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstContainment HYDRACONST_16_0_0_1 = new hydraconstraints.resource.hydraConst.grammar.HydraConstContainment(hydraconstraints.HydraconstraintsPackage.eINSTANCE.getAll().getEStructuralFeature(hydraconstraints.HydraconstraintsPackage.ALL__SELECTION_OP), hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE, 0);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstSequence HYDRACONST_16_0_0 = new hydraconstraints.resource.hydraConst.grammar.HydraConstSequence(hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE, HYDRACONST_16_0_0_0, HYDRACONST_16_0_0_1);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstChoice HYDRACONST_16_0 = new hydraconstraints.resource.hydraConst.grammar.HydraConstChoice(hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE, HYDRACONST_16_0_0);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstRule HYDRACONST_16 = new hydraconstraints.resource.hydraConst.grammar.HydraConstRule(hydraconstraints.HydraconstraintsPackage.eINSTANCE.getAll(), HYDRACONST_16_0, hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstKeyword HYDRACONST_17_0_0_0 = new hydraconstraints.resource.hydraConst.grammar.HydraConstKeyword("any", hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstContainment HYDRACONST_17_0_0_1 = new hydraconstraints.resource.hydraConst.grammar.HydraConstContainment(hydraconstraints.HydraconstraintsPackage.eINSTANCE.getAny().getEStructuralFeature(hydraconstraints.HydraconstraintsPackage.ANY__SELECTION_OP), hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE, 0);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstSequence HYDRACONST_17_0_0 = new hydraconstraints.resource.hydraConst.grammar.HydraConstSequence(hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE, HYDRACONST_17_0_0_0, HYDRACONST_17_0_0_1);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstChoice HYDRACONST_17_0 = new hydraconstraints.resource.hydraConst.grammar.HydraConstChoice(hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE, HYDRACONST_17_0_0);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstRule HYDRACONST_17 = new hydraconstraints.resource.hydraConst.grammar.HydraConstRule(hydraconstraints.HydraconstraintsPackage.eINSTANCE.getAny(), HYDRACONST_17_0, hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstContainment HYDRACONST_18_0_0_0 = new hydraconstraints.resource.hydraConst.grammar.HydraConstContainment(hydraconstraints.HydraconstraintsPackage.eINSTANCE.getMore().getEStructuralFeature(hydraconstraints.HydraconstraintsPackage.MORE__COMP_OP1), hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE, 0);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstKeyword HYDRACONST_18_0_0_1 = new hydraconstraints.resource.hydraConst.grammar.HydraConstKeyword(">", hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstContainment HYDRACONST_18_0_0_2 = new hydraconstraints.resource.hydraConst.grammar.HydraConstContainment(hydraconstraints.HydraconstraintsPackage.eINSTANCE.getMore().getEStructuralFeature(hydraconstraints.HydraconstraintsPackage.MORE__COMP_OP2), hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE, 0);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstSequence HYDRACONST_18_0_0 = new hydraconstraints.resource.hydraConst.grammar.HydraConstSequence(hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE, HYDRACONST_18_0_0_0, HYDRACONST_18_0_0_1, HYDRACONST_18_0_0_2);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstChoice HYDRACONST_18_0 = new hydraconstraints.resource.hydraConst.grammar.HydraConstChoice(hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE, HYDRACONST_18_0_0);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstRule HYDRACONST_18 = new hydraconstraints.resource.hydraConst.grammar.HydraConstRule(hydraconstraints.HydraconstraintsPackage.eINSTANCE.getMore(), HYDRACONST_18_0, hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstContainment HYDRACONST_19_0_0_0 = new hydraconstraints.resource.hydraConst.grammar.HydraConstContainment(hydraconstraints.HydraconstraintsPackage.eINSTANCE.getMoreOrEqual().getEStructuralFeature(hydraconstraints.HydraconstraintsPackage.MORE_OR_EQUAL__COMP_OP1), hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE, 0);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstKeyword HYDRACONST_19_0_0_1 = new hydraconstraints.resource.hydraConst.grammar.HydraConstKeyword(">=", hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstContainment HYDRACONST_19_0_0_2 = new hydraconstraints.resource.hydraConst.grammar.HydraConstContainment(hydraconstraints.HydraconstraintsPackage.eINSTANCE.getMoreOrEqual().getEStructuralFeature(hydraconstraints.HydraconstraintsPackage.MORE_OR_EQUAL__COMP_OP2), hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE, 0);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstSequence HYDRACONST_19_0_0 = new hydraconstraints.resource.hydraConst.grammar.HydraConstSequence(hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE, HYDRACONST_19_0_0_0, HYDRACONST_19_0_0_1, HYDRACONST_19_0_0_2);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstChoice HYDRACONST_19_0 = new hydraconstraints.resource.hydraConst.grammar.HydraConstChoice(hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE, HYDRACONST_19_0_0);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstRule HYDRACONST_19 = new hydraconstraints.resource.hydraConst.grammar.HydraConstRule(hydraconstraints.HydraconstraintsPackage.eINSTANCE.getMoreOrEqual(), HYDRACONST_19_0, hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstContainment HYDRACONST_20_0_0_0 = new hydraconstraints.resource.hydraConst.grammar.HydraConstContainment(hydraconstraints.HydraconstraintsPackage.eINSTANCE.getLess().getEStructuralFeature(hydraconstraints.HydraconstraintsPackage.LESS__COMP_OP1), hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE, 0);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstKeyword HYDRACONST_20_0_0_1 = new hydraconstraints.resource.hydraConst.grammar.HydraConstKeyword("<", hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstContainment HYDRACONST_20_0_0_2 = new hydraconstraints.resource.hydraConst.grammar.HydraConstContainment(hydraconstraints.HydraconstraintsPackage.eINSTANCE.getLess().getEStructuralFeature(hydraconstraints.HydraconstraintsPackage.LESS__COMP_OP2), hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE, 0);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstSequence HYDRACONST_20_0_0 = new hydraconstraints.resource.hydraConst.grammar.HydraConstSequence(hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE, HYDRACONST_20_0_0_0, HYDRACONST_20_0_0_1, HYDRACONST_20_0_0_2);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstChoice HYDRACONST_20_0 = new hydraconstraints.resource.hydraConst.grammar.HydraConstChoice(hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE, HYDRACONST_20_0_0);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstRule HYDRACONST_20 = new hydraconstraints.resource.hydraConst.grammar.HydraConstRule(hydraconstraints.HydraconstraintsPackage.eINSTANCE.getLess(), HYDRACONST_20_0, hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstContainment HYDRACONST_21_0_0_0 = new hydraconstraints.resource.hydraConst.grammar.HydraConstContainment(hydraconstraints.HydraconstraintsPackage.eINSTANCE.getLessOrEqual().getEStructuralFeature(hydraconstraints.HydraconstraintsPackage.LESS_OR_EQUAL__COMP_OP1), hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE, 0);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstKeyword HYDRACONST_21_0_0_1 = new hydraconstraints.resource.hydraConst.grammar.HydraConstKeyword("<=", hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstContainment HYDRACONST_21_0_0_2 = new hydraconstraints.resource.hydraConst.grammar.HydraConstContainment(hydraconstraints.HydraconstraintsPackage.eINSTANCE.getLessOrEqual().getEStructuralFeature(hydraconstraints.HydraconstraintsPackage.LESS_OR_EQUAL__COMP_OP2), hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE, 0);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstSequence HYDRACONST_21_0_0 = new hydraconstraints.resource.hydraConst.grammar.HydraConstSequence(hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE, HYDRACONST_21_0_0_0, HYDRACONST_21_0_0_1, HYDRACONST_21_0_0_2);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstChoice HYDRACONST_21_0 = new hydraconstraints.resource.hydraConst.grammar.HydraConstChoice(hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE, HYDRACONST_21_0_0);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstRule HYDRACONST_21 = new hydraconstraints.resource.hydraConst.grammar.HydraConstRule(hydraconstraints.HydraconstraintsPackage.eINSTANCE.getLessOrEqual(), HYDRACONST_21_0, hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstContainment HYDRACONST_22_0_0_0 = new hydraconstraints.resource.hydraConst.grammar.HydraConstContainment(hydraconstraints.HydraconstraintsPackage.eINSTANCE.getNotEqual().getEStructuralFeature(hydraconstraints.HydraconstraintsPackage.NOT_EQUAL__COMP_OP1), hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE, 0);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstKeyword HYDRACONST_22_0_0_1 = new hydraconstraints.resource.hydraConst.grammar.HydraConstKeyword("!=", hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstContainment HYDRACONST_22_0_0_2 = new hydraconstraints.resource.hydraConst.grammar.HydraConstContainment(hydraconstraints.HydraconstraintsPackage.eINSTANCE.getNotEqual().getEStructuralFeature(hydraconstraints.HydraconstraintsPackage.NOT_EQUAL__COMP_OP2), hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE, 0);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstSequence HYDRACONST_22_0_0 = new hydraconstraints.resource.hydraConst.grammar.HydraConstSequence(hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE, HYDRACONST_22_0_0_0, HYDRACONST_22_0_0_1, HYDRACONST_22_0_0_2);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstChoice HYDRACONST_22_0 = new hydraconstraints.resource.hydraConst.grammar.HydraConstChoice(hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE, HYDRACONST_22_0_0);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstRule HYDRACONST_22 = new hydraconstraints.resource.hydraConst.grammar.HydraConstRule(hydraconstraints.HydraconstraintsPackage.eINSTANCE.getNotEqual(), HYDRACONST_22_0, hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstContainment HYDRACONST_23_0_0_0 = new hydraconstraints.resource.hydraConst.grammar.HydraConstContainment(hydraconstraints.HydraconstraintsPackage.eINSTANCE.getEqual().getEStructuralFeature(hydraconstraints.HydraconstraintsPackage.EQUAL__COMP_OP1), hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE, 0);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstKeyword HYDRACONST_23_0_0_1 = new hydraconstraints.resource.hydraConst.grammar.HydraConstKeyword("==", hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstContainment HYDRACONST_23_0_0_2 = new hydraconstraints.resource.hydraConst.grammar.HydraConstContainment(hydraconstraints.HydraconstraintsPackage.eINSTANCE.getEqual().getEStructuralFeature(hydraconstraints.HydraconstraintsPackage.EQUAL__COMP_OP2), hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE, 0);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstSequence HYDRACONST_23_0_0 = new hydraconstraints.resource.hydraConst.grammar.HydraConstSequence(hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE, HYDRACONST_23_0_0_0, HYDRACONST_23_0_0_1, HYDRACONST_23_0_0_2);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstChoice HYDRACONST_23_0 = new hydraconstraints.resource.hydraConst.grammar.HydraConstChoice(hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE, HYDRACONST_23_0_0);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstRule HYDRACONST_23 = new hydraconstraints.resource.hydraConst.grammar.HydraConstRule(hydraconstraints.HydraconstraintsPackage.eINSTANCE.getEqual(), HYDRACONST_23_0, hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstPlaceholder HYDRACONST_24_0_0_0 = new hydraconstraints.resource.hydraConst.grammar.HydraConstPlaceholder(hydraconstraints.HydraconstraintsPackage.eINSTANCE.getSimpleFeature().getEStructuralFeature(hydraconstraints.HydraconstraintsPackage.SIMPLE_FEATURE__FEATURE_NAME), "TEXT", hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE, 0);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstSequence HYDRACONST_24_0_0 = new hydraconstraints.resource.hydraConst.grammar.HydraConstSequence(hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE, HYDRACONST_24_0_0_0);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstChoice HYDRACONST_24_0 = new hydraconstraints.resource.hydraConst.grammar.HydraConstChoice(hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE, HYDRACONST_24_0_0);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstRule HYDRACONST_24 = new hydraconstraints.resource.hydraConst.grammar.HydraConstRule(hydraconstraints.HydraconstraintsPackage.eINSTANCE.getSimpleFeature(), HYDRACONST_24_0, hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstPlaceholder HYDRACONST_25_0_0_0 = new hydraconstraints.resource.hydraConst.grammar.HydraConstPlaceholder(hydraconstraints.HydraconstraintsPackage.eINSTANCE.getMultipleFeature().getEStructuralFeature(hydraconstraints.HydraconstraintsPackage.MULTIPLE_FEATURE__FEATURE_NAME), "TEXT", hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE, 0);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstSequence HYDRACONST_25_0_0 = new hydraconstraints.resource.hydraConst.grammar.HydraConstSequence(hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE, HYDRACONST_25_0_0_0);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstChoice HYDRACONST_25_0 = new hydraconstraints.resource.hydraConst.grammar.HydraConstChoice(hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE, HYDRACONST_25_0_0);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstRule HYDRACONST_25 = new hydraconstraints.resource.hydraConst.grammar.HydraConstRule(hydraconstraints.HydraconstraintsPackage.eINSTANCE.getMultipleFeature(), HYDRACONST_25_0, hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstPlaceholder HYDRACONST_26_0_0_0 = new hydraconstraints.resource.hydraConst.grammar.HydraConstPlaceholder(hydraconstraints.HydraconstraintsPackage.eINSTANCE.getNumber().getEStructuralFeature(hydraconstraints.HydraconstraintsPackage.NUMBER__NUM_VALUE), "DIGIT", hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE, 0);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstSequence HYDRACONST_26_0_0 = new hydraconstraints.resource.hydraConst.grammar.HydraConstSequence(hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE, HYDRACONST_26_0_0_0);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstChoice HYDRACONST_26_0 = new hydraconstraints.resource.hydraConst.grammar.HydraConstChoice(hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE, HYDRACONST_26_0_0);
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstRule HYDRACONST_26 = new hydraconstraints.resource.hydraConst.grammar.HydraConstRule(hydraconstraints.HydraconstraintsPackage.eINSTANCE.getNumber(), HYDRACONST_26_0, hydraconstraints.resource.hydraConst.grammar.HydraConstCardinality.ONE);
	
	public final static hydraconstraints.resource.hydraConst.grammar.HydraConstRule[] RULES = new hydraconstraints.resource.hydraConst.grammar.HydraConstRule[] {
		HYDRACONST_0,
		HYDRACONST_1,
		HYDRACONST_2,
		HYDRACONST_3,
		HYDRACONST_4,
		HYDRACONST_5,
		HYDRACONST_6,
		HYDRACONST_7,
		HYDRACONST_8,
		HYDRACONST_9,
		HYDRACONST_10,
		HYDRACONST_11,
		HYDRACONST_12,
		HYDRACONST_13,
		HYDRACONST_14,
		HYDRACONST_15,
		HYDRACONST_16,
		HYDRACONST_17,
		HYDRACONST_18,
		HYDRACONST_19,
		HYDRACONST_20,
		HYDRACONST_21,
		HYDRACONST_22,
		HYDRACONST_23,
		HYDRACONST_24,
		HYDRACONST_25,
		HYDRACONST_26,
	};
	
	/**
	 * Returns all keywords of the grammar. This includes all literals for boolean and
	 * enumeration terminals.
	 */
	public java.util.Set<String> getKeywords() {
		if (this.keywords == null) {
			this.keywords = new java.util.LinkedHashSet<String>();
			for (hydraconstraints.resource.hydraConst.grammar.HydraConstRule rule : RULES) {
				findKeywords(rule, this.keywords);
			}
		}
		return keywords;
	}
	
	/**
	 * Finds all keywords in the given element and its children and adds them to the
	 * set. This includes all literals for boolean and enumeration terminals.
	 */
	private void findKeywords(hydraconstraints.resource.hydraConst.grammar.HydraConstSyntaxElement element, java.util.Set<String> keywords) {
		if (element instanceof hydraconstraints.resource.hydraConst.grammar.HydraConstKeyword) {
			keywords.add(((hydraconstraints.resource.hydraConst.grammar.HydraConstKeyword) element).getValue());
		} else if (element instanceof hydraconstraints.resource.hydraConst.grammar.HydraConstBooleanTerminal) {
			keywords.add(((hydraconstraints.resource.hydraConst.grammar.HydraConstBooleanTerminal) element).getTrueLiteral());
			keywords.add(((hydraconstraints.resource.hydraConst.grammar.HydraConstBooleanTerminal) element).getFalseLiteral());
		} else if (element instanceof hydraconstraints.resource.hydraConst.grammar.HydraConstEnumerationTerminal) {
			hydraconstraints.resource.hydraConst.grammar.HydraConstEnumerationTerminal terminal = (hydraconstraints.resource.hydraConst.grammar.HydraConstEnumerationTerminal) element;
			for (String key : terminal.getLiteralMapping().keySet()) {
				keywords.add(key);
			}
		}
		for (hydraconstraints.resource.hydraConst.grammar.HydraConstSyntaxElement child : element.getChildren()) {
			findKeywords(child, this.keywords);
		}
	}
	
}
